include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - ".dart_tool/**"
    - "flutter/**"
    - "functions/node_modules/**"
    - "distribution/**"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - always_declare_return_types
    - avoid_print
