-- Fufaji Backend - Initial Database Schema
-- Run this in Supabase SQL Editor to set up the entire database
-- Created: 2026-06-21

-- ============================================================================
-- 1. USERS TABLE
-- ============================================================================

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  firebase_uid VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(50) NOT NULL
    CHECK (role IN ('customer', 'owner', 'rider', 'employee', 'admin')),
  shop_id UUID REFERENCES shops(id),
  name VARCHAR(255),
  profile_image_url VARCHAR(500),

  -- Account status
  is_active BOOLEAN DEFAULT TRUE,
  phone_verified BOOLEAN DEFAULT FALSE,
  email_verified BOOLEAN DEFAULT FALSE,

  -- Metadata
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  CONSTRAINT valid_shop_for_owner CHECK (
    (role != 'owner' AND shop_id IS NULL) OR (role = 'owner' AND shop_id IS NOT NULL)
  )
);

CREATE INDEX idx_users_firebase_uid ON users(firebase_uid);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_shop_id ON users(shop_id);
CREATE INDEX idx_users_role ON users(role);


-- ============================================================================
-- 2. SHOPS TABLE
-- ============================================================================

CREATE TABLE shops (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,

  -- Location
  location_lat DECIMAL(10, 8) NOT NULL,
  location_long DECIMAL(11, 8) NOT NULL,
  address VARCHAR(500),
  city VARCHAR(100),
  pincode VARCHAR(10),

  -- Branding
  logo_url VARCHAR(500),
  banner_image_url VARCHAR(500),
  primary_color VARCHAR(7),

  -- Metadata
  rating DECIMAL(3, 2) DEFAULT 0,
  total_orders INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_shops_owner_id ON shops(owner_id);
CREATE INDEX idx_shops_is_active ON shops(is_active);
CREATE INDEX idx_shops_location ON shops(location_lat, location_long);


-- ============================================================================
-- 3. PRODUCTS TABLE
-- ============================================================================

CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,

  -- Basic info
  name VARCHAR(255) NOT NULL,
  description TEXT,
  sku VARCHAR(100),

  -- Pricing
  price DECIMAL(10, 2) NOT NULL,
  cost_price DECIMAL(10, 2),
  tax_percentage DECIMAL(5, 2) DEFAULT 0,

  -- Media
  image_url VARCHAR(500),
  category VARCHAR(100),
  tags VARCHAR(255), -- CSV: "dairy,milk,cold"

  -- Availability
  is_active BOOLEAN DEFAULT TRUE,

  -- Metadata
  rating DECIMAL(3, 2) DEFAULT 0,
  total_ratings INT DEFAULT 0,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_products_shop_id ON products(shop_id);
CREATE INDEX idx_products_is_active ON products(is_active);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_category ON products(category);


-- ============================================================================
-- 4. INVENTORY STOCK TABLE
-- ============================================================================

CREATE TABLE inventory_stock (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  shop_id UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,

  -- Stock levels
  total_qty INT NOT NULL DEFAULT 0,        -- Total units
  available_qty INT NOT NULL DEFAULT 0,    -- available = total - reserved - sold
  reserved_qty INT NOT NULL DEFAULT 0,     -- Locked for pending orders
  sold_qty INT NOT NULL DEFAULT 0,         -- Already sold

  last_updated TIMESTAMP DEFAULT NOW(),

  CONSTRAINT valid_stock CHECK (
    available_qty >= 0
    AND reserved_qty >= 0
    AND sold_qty >= 0
  )
);

CREATE INDEX idx_inventory_stock_product_id ON inventory_stock(product_id);
CREATE INDEX idx_inventory_stock_shop_id ON inventory_stock(shop_id);


-- ============================================================================
-- 5. ORDERS TABLE (UNIFIED - Single source of truth)
-- ============================================================================

CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identifiers
  order_number VARCHAR(50) UNIQUE NOT NULL, -- Generated by backend
  customer_id UUID NOT NULL REFERENCES users(id),
  shop_id UUID NOT NULL REFERENCES shops(id),

  -- Order content (stored as JSON for flexibility)
  items JSONB NOT NULL, -- [{product_id, quantity, price_at_purchase}, ...]

  -- Pricing breakdown
  total_amount DECIMAL(10, 2) NOT NULL,     -- Sum of (qty × price)
  discount_amount DECIMAL(10, 2) DEFAULT 0,
  tax_amount DECIMAL(10, 2) DEFAULT 0,
  delivery_charge DECIMAL(10, 2) DEFAULT 0,
  final_amount DECIMAL(10, 2) NOT NULL,     -- total - discount + tax + delivery

  -- Order type (unifies 4 engines)
  order_type VARCHAR(50) DEFAULT 'normal' CHECK (order_type IN (
    'normal',      -- Regular cart order
    'wallet',      -- Wallet order
    'group_buy',   -- Group buying
    'reorder'      -- Quick reorder
  )),

  -- Order status (single state machine for all types)
  status VARCHAR(50) NOT NULL DEFAULT 'pending_payment' CHECK (status IN (
    'pending_payment',      -- Awaiting payment
    'payment_verified',     -- Payment confirmed
    'ready_to_pack',        -- Ready for fulfillment
    'picked',               -- Items picked
    'packed',               -- Items packed
    'assigned_to_delivery', -- Rider assigned
    'picked_up',            -- Rider picked up
    'in_transit',           -- On the way
    'delivered',            -- Successfully delivered
    'cancelled',            -- Order cancelled
    'refunded'              -- Refund processed
  )),

  -- Delivery info
  delivery_address JSONB NOT NULL, -- {street, city, pincode, lat, lng}
  delivery_instructions TEXT,
  estimated_delivery_time TIMESTAMP,
  assigned_rider_id UUID REFERENCES users(id),

  -- Payment info
  payment_method VARCHAR(50) DEFAULT 'razorpay' CHECK (payment_method IN (
    'razorpay',
    'stripe',
    'wallet',
    'cash'
  )),
  razorpay_order_id VARCHAR(255),
  razorpay_payment_id VARCHAR(255),
  payment_verified_at TIMESTAMP,

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  -- Constraints
  CONSTRAINT valid_amounts CHECK (
    final_amount = (total_amount - discount_amount + tax_amount + delivery_charge)
  ),
  CONSTRAINT valid_delivery_for_status CHECK (
    (status NOT IN ('delivered', 'in_transit', 'picked_up') OR assigned_rider_id IS NOT NULL)
  )
);

CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_shop_id ON orders(shop_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_order_type ON orders(order_type);
CREATE INDEX idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX idx_orders_assigned_rider_id ON orders(assigned_rider_id);
CREATE INDEX idx_orders_order_number ON orders(order_number);


-- ============================================================================
-- 6. PAYMENTS TABLE
-- ============================================================================

CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,

  -- Payment identifiers
  razorpay_payment_id VARCHAR(255),
  razorpay_order_id VARCHAR(255),

  amount DECIMAL(10, 2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'INR',
  payment_method VARCHAR(50),

  -- Payment state machine
  status VARCHAR(50) NOT NULL DEFAULT 'created' CHECK (status IN (
    'created',      -- Payment initiated
    'authorized',   -- Authorized (captured pending)
    'captured',     -- Successfully captured
    'failed',       -- Payment failed
    'refunded'      -- Refunded to customer
  )),

  -- Webhook security
  razorpay_signature VARCHAR(255),
  signature_verified BOOLEAN DEFAULT FALSE,
  webhook_received_at TIMESTAMP,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_payments_order_id ON payments(order_id);
CREATE INDEX idx_payments_razorpay_payment_id ON payments(razorpay_payment_id);
CREATE INDEX idx_payments_status ON payments(status);


-- ============================================================================
-- 7. REFUNDS TABLE
-- ============================================================================

CREATE TABLE refunds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  payment_id UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,

  -- Refund details
  amount DECIMAL(10, 2) NOT NULL,
  reason VARCHAR(255), -- 'customer_cancel', 'payment_failed', 'item_unavailable'

  -- Refund status
  status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending',      -- Refund initiated
    'processed',    -- Successfully refunded
    'failed'        -- Refund failed
  )),

  -- What was restored
  refund_to_wallet BOOLEAN DEFAULT TRUE,
  stock_restored BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX idx_refunds_order_id ON refunds(order_id);
CREATE INDEX idx_refunds_payment_id ON refunds(payment_id);
CREATE INDEX idx_refunds_status ON refunds(status);


-- ============================================================================
-- 8. PACKING TASKS TABLE (Unified fulfillment workflow)
-- ============================================================================

CREATE TABLE packing_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  shop_id UUID NOT NULL REFERENCES shops(id),

  -- Task status (single state machine)
  status VARCHAR(50) NOT NULL DEFAULT 'ready_to_pick' CHECK (status IN (
    'ready_to_pick',  -- Waiting for employee
    'picked',         -- Items picked from shelf
    'packed',         -- Items packed in box
    'handed_off'      -- Handed to delivery
  )),

  -- Items being packed (JSON for flexibility)
  items JSONB NOT NULL, -- [{product_id, qty, picked_qty}, ...]

  -- Packing employee
  packed_by_employee_id UUID REFERENCES users(id),

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  picked_at TIMESTAMP,
  packed_at TIMESTAMP,
  handed_off_at TIMESTAMP,

  CONSTRAINT consistent_status CHECK (
    (status = 'ready_to_pick' AND picked_at IS NULL) OR
    (status IN ('picked', 'packed', 'handed_off') AND picked_at IS NOT NULL) OR
    (status IN ('packed', 'handed_off') AND packed_at IS NOT NULL)
  )
);

CREATE INDEX idx_packing_tasks_order_id ON packing_tasks(order_id);
CREATE INDEX idx_packing_tasks_shop_id ON packing_tasks(shop_id);
CREATE INDEX idx_packing_tasks_status ON packing_tasks(status);
CREATE INDEX idx_packing_tasks_created_at ON packing_tasks(created_at);


-- ============================================================================
-- 9. DELIVERY ASSIGNMENTS TABLE (Unified delivery service)
-- ============================================================================

CREATE TABLE delivery_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  rider_id UUID NOT NULL REFERENCES users(id),

  -- Delivery status (single state machine)
  status VARCHAR(50) NOT NULL DEFAULT 'assigned' CHECK (status IN (
    'assigned',     -- Assigned to rider
    'picked_up',    -- Rider picked up from shop
    'in_transit',   -- On the way to customer
    'delivered',    -- Delivered to customer
    'failed'        -- Delivery failed
  )),

  -- Locations
  pickup_location JSONB NOT NULL,    -- Shop location
  delivery_location JSONB NOT NULL,  -- Customer location

  -- Timestamps
  assigned_at TIMESTAMP DEFAULT NOW(),
  picked_up_at TIMESTAMP,
  delivered_at TIMESTAMP,

  updated_at TIMESTAMP DEFAULT NOW(),

  CONSTRAINT valid_timestamps CHECK (
    (status = 'assigned' AND picked_up_at IS NULL AND delivered_at IS NULL) OR
    (status IN ('picked_up', 'in_transit', 'delivered', 'failed') AND picked_up_at IS NOT NULL)
  )
);

CREATE INDEX idx_delivery_assignments_order_id ON delivery_assignments(order_id);
CREATE INDEX idx_delivery_assignments_rider_id ON delivery_assignments(rider_id);
CREATE INDEX idx_delivery_assignments_status ON delivery_assignments(status);


-- ============================================================================
-- 10. COUPONS TABLE (Firestore RLS will enforce read-only)
-- ============================================================================

CREATE TABLE coupons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,

  code VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,

  -- Discount
  discount_type VARCHAR(50) CHECK (discount_type IN ('fixed', 'percentage')),
  discount_value DECIMAL(10, 2) NOT NULL,
  max_discount DECIMAL(10, 2),

  -- Validity
  valid_from TIMESTAMP NOT NULL,
  valid_until TIMESTAMP NOT NULL,
  usage_limit INT,
  usage_count INT DEFAULT 0,

  is_active BOOLEAN DEFAULT TRUE,

  created_at TIMESTAMP DEFAULT NOW(),

  CONSTRAINT valid_coupon_period CHECK (valid_from < valid_until),
  CONSTRAINT positive_discount CHECK (discount_value > 0)
);

CREATE INDEX idx_coupons_shop_id ON coupons(shop_id);
CREATE INDEX idx_coupons_code ON coupons(code);
CREATE INDEX idx_coupons_is_active ON coupons(is_active);


-- ============================================================================
-- 11. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE packing_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

-- Users: Can only see their own profile
CREATE POLICY "Users can view own profile" ON users
  FOR SELECT USING (auth.uid()::text = firebase_uid);

-- Shops: Public read, owner can write
CREATE POLICY "Shops are public" ON shops
  FOR SELECT USING (true);

CREATE POLICY "Shop owners can update own shop" ON shops
  FOR UPDATE USING (auth.uid()::text = (
    SELECT firebase_uid FROM users WHERE users.id = owner_id
  ));

-- Products: Public read, owner can write
CREATE POLICY "Products are public" ON products
  FOR SELECT USING (true);

CREATE POLICY "Shop owners can manage products" ON products
  FOR UPDATE USING (auth.uid()::text = (
    SELECT firebase_uid FROM users WHERE users.id =
      (SELECT owner_id FROM shops WHERE shops.id = products.shop_id)
  ));

-- Orders: Customers see own, owners see shop's
CREATE POLICY "Customers see own orders" ON orders
  FOR SELECT USING (
    customer_id = (SELECT id FROM users WHERE firebase_uid = auth.uid()::text)
  );

CREATE POLICY "Shop owners see shop orders" ON orders
  FOR SELECT USING (
    shop_id IN (SELECT id FROM shops WHERE owner_id = (
      SELECT id FROM users WHERE firebase_uid = auth.uid()::text
    ))
  );

-- Riders see assigned delivery orders
CREATE POLICY "Riders see assigned orders" ON orders
  FOR SELECT USING (
    assigned_rider_id = (SELECT id FROM users WHERE firebase_uid = auth.uid()::text)
  );

-- Coupons: Public read only
CREATE POLICY "Coupons are public" ON coupons
  FOR SELECT USING (true);

-- Delivery assignments: Riders see own, orders see if assigned
CREATE POLICY "Riders see own assignments" ON delivery_assignments
  FOR SELECT USING (
    rider_id = (SELECT id FROM users WHERE firebase_uid = auth.uid()::text)
  );

-- ============================================================================
-- 12. TRIGGERS (Automatic syncing & updates)
-- ============================================================================

-- Function: Update order.updated_at on any change
CREATE OR REPLACE FUNCTION update_orders_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_update_timestamp
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_orders_timestamp();

-- Function: Update payments.updated_at
CREATE OR REPLACE FUNCTION update_payments_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER payments_update_timestamp
  BEFORE UPDATE ON payments
  FOR EACH ROW
  EXECUTE FUNCTION update_payments_timestamp();

-- Function: Update delivery_assignments.updated_at
CREATE OR REPLACE FUNCTION update_delivery_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER delivery_assignments_update_timestamp
  BEFORE UPDATE ON delivery_assignments
  FOR EACH ROW
  EXECUTE FUNCTION update_delivery_timestamp();

-- ============================================================================
-- 13. SAMPLE DATA (for testing)
-- ============================================================================

-- Create test shop owner
INSERT INTO users (firebase_uid, phone, email, role, name)
VALUES ('test_owner_123', '9999999990', 'owner@test.com', 'owner', 'Test Owner');

-- Create test shop
INSERT INTO shops (owner_id, name, location_lat, location_long, address)
SELECT id, 'Test Shop', 28.6139, 77.2090, '123 Main St'
FROM users WHERE email = 'owner@test.com';

-- Create test customer
INSERT INTO users (firebase_uid, phone, email, role, name)
VALUES ('test_customer_123', '9999999991', 'customer@test.com', 'customer', 'Test Customer');

-- Create test rider
INSERT INTO users (firebase_uid, phone, email, role, name)
VALUES ('test_rider_123', '9999999992', 'rider@test.com', 'rider', 'Test Rider');

-- Create test product
INSERT INTO products (shop_id, name, price, description, category)
SELECT id, 'Test Milk', 50.00, 'Fresh milk', 'Dairy'
FROM shops WHERE name = 'Test Shop';

-- Create test inventory
INSERT INTO inventory_stock (product_id, shop_id, total_qty, available_qty, reserved_qty)
SELECT p.id, p.shop_id, 100, 100, 0
FROM products p WHERE p.name = 'Test Milk';

-- ============================================================================
-- ALL DONE!
-- ============================================================================
-- Your database is now ready for:
-- ✓ Orders (unified across 4 types)
-- ✓ Payments (Razorpay + Stripe)
-- ✓ Inventory management
-- ✓ Fulfillment (packing)
-- ✓ Delivery assignment
-- ✓ Refunds
-- ✓ RLS security
--
-- Next steps:
-- 1. Create Firestore collections (see BACKEND_ARCHITECTURE.md)
-- 2. Set Firestore security rules
-- 3. Build Dart backend services
-- 4. Test API endpoints
