import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'device_security_service.dart';
import '../providers/auth_provider.dart';

/// MutationService
///
/// Wraps Firestore mutations with rich client metadata (Device, User, Version).
/// This allows backend Cloud Functions to reliably generate Event Sourcing Audit Logs
/// enriched with this metadata.
///
/// DO NOT USE this as the final audit log. The source-of-truth audit log
/// MUST be generated by Firestore triggers in Cloud Functions.
class MutationService {
  static final MutationService _instance = MutationService._internal();
  factory MutationService() => _instance;
  MutationService._internal();
  Future<Map<String, dynamic>> _getClientMetadata() async {
    String deviceId = 'unknown';
    String appVersion = 'unknown';
    
    try {
      deviceId = await DeviceSecurityService.getDeviceId();
      final packageInfo = await PackageInfo.fromPlatform();
      appVersion = '${packageInfo.version}+${packageInfo.buildNumber}';
    } catch (_) {}

    final auth = AuthProvider.instance;
    final userId = auth.currentUser?.id ?? 'unauthenticated';
    final branchId = auth.currentUser?.branchId ?? 'global';
    final sessionId = auth.currentSessionId ?? 'no_session';

    return {
      '_meta_deviceId': deviceId,
      '_meta_appVersion': appVersion,
      '_meta_userId': userId,
      '_meta_branchId': branchId,
      '_meta_sessionId': sessionId,
      '_meta_timestamp': FieldValue.serverTimestamp(),
    };
  }

  /// Sets a document, merging metadata
  Future<void> setDocument(DocumentReference ref, Map<String, dynamic> data, {SetOptions? options}) async {
    final meta = await _getClientMetadata();
    final enrichedData = Map<String, dynamic>.from(data)..addAll(meta);
    await ref.set(enrichedData, options);
  }

  /// Updates a document, merging metadata
  Future<void> updateDocument(DocumentReference ref, Map<String, dynamic> data) async {
    final meta = await _getClientMetadata();
    final enrichedData = Map<String, dynamic>.from(data)..addAll(meta);
    await ref.update(enrichedData);
  }

  /// Adds a document to a collection, merging metadata
  Future<DocumentReference> addDocument(CollectionReference ref, Map<String, dynamic> data) async {
    final meta = await _getClientMetadata();
    final enrichedData = Map<String, dynamic>.from(data)..addAll(meta);
    return await ref.add(enrichedData);
  }
}
