import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

import '../models/payout_request_model.dart';
import 'rider_payout_service.dart';

/// Owner-facing service for reviewing and resolving automated payout
/// requests (Task #53).
///
/// Requests themselves are generated by the `generatePayoutRequests`
/// scheduled Cloud Function (see `functions/src/automation/cronJobs.ts`),
/// which writes documents to the `payout_requests` collection with
/// `status: 'pending'`. Nothing leaves the business's account until an
/// owner explicitly approves a request here — consistent with the
/// "owner review and approval before write/payout" policy used across
/// the inventory change-request flow (Tasks #116-122).
class PayoutRequestService {
  static final PayoutRequestService _instance = PayoutRequestService._internal();
  factory PayoutRequestService() => _instance;
  PayoutRequestService._internal();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final RiderPayoutService _riderPayoutService = RiderPayoutService();

  static const String _collection = 'payout_requests';

  /// Streams all pending payout requests, newest first.
  Stream<List<PayoutRequestModel>> getPendingRequestsStream() {
    return _firestore
        .collection(_collection)
        .where('status', isEqualTo: PayoutRequestStatus.pending.name)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) => snap.docs.map((d) => PayoutRequestModel.fromMap(d.data(), d.id)).toList());
  }

  /// Streams all resolved (approved/paid/rejected/failed) payout requests,
  /// for the history view.
  Stream<List<PayoutRequestModel>> getHistoryStream({int limit = 50}) {
    return _firestore
        .collection(_collection)
        .where(
          'status',
          whereIn: [
            PayoutRequestStatus.approved.name,
            PayoutRequestStatus.paid.name,
            PayoutRequestStatus.rejected.name,
            PayoutRequestStatus.failed.name,
          ],
        )
        .orderBy('createdAt', descending: true)
        .limit(limit)
        .snapshots()
        .map((snap) => snap.docs.map((d) => PayoutRequestModel.fromMap(d.data(), d.id)).toList());
  }

  /// Rejects a payout request (rider or vendor). The underlying orders
  /// remain unattached so they can be re-aggregated into a future request
  /// (the cron job only excludes orders already attached to a *non-rejected*
  /// request).
  Future<void> rejectRequest({
    required PayoutRequestModel request,
    required String ownerUid,
    String? reason,
  }) async {
    await _firestore.collection(_collection).doc(request.id).update({
      'status': PayoutRequestStatus.rejected.name,
      'resolvedAt': FieldValue.serverTimestamp(),
      'resolvedBy': ownerUid,
      'notes': reason,
    });
  }

  /// Approves a rider payout request and immediately triggers the existing
  /// Razorpay Route instant-payout flow ([RiderPayoutService.initiateInstantPayout]).
  ///
  /// On success the request is marked `paid` with the resulting
  /// transaction ID. On failure it is marked `failed` with the error
  /// message so the owner can retry once the underlying issue (e.g.
  /// missing bank details) is fixed — the cron job will not regenerate a
  /// duplicate request for the same orders while this one exists.
  Future<PayoutResult> approveRiderRequest({
    required PayoutRequestModel request,
    required String ownerUid,
  }) async {
    if (request.type != PayoutRequestType.rider) {
      return PayoutResult(success: false, message: 'Not a rider payout request');
    }

    // Mark approved first so the UI reflects the in-progress state and the
    // cron job does not pick these orders up again concurrently.
    await _firestore.collection(_collection).doc(request.id).update({
      'status': PayoutRequestStatus.approved.name,
      'resolvedAt': FieldValue.serverTimestamp(),
      'resolvedBy': ownerUid,
    });

    try {
      final result = await _riderPayoutService.initiateInstantPayout(
        riderId: request.recipientId,
        riderName: request.recipientName,
        amount: request.amount.toDouble(),
        currency: request.currency,
      );

      if (result.success) {
        await _firestore.collection(_collection).doc(request.id).update({
          'status': PayoutRequestStatus.paid.name,
          'transactionId': result.transactionId,
        });
      } else {
        await _firestore.collection(_collection).doc(request.id).update({
          'status': PayoutRequestStatus.failed.name,
          'errorMessage': result.message,
        });
      }
      return result;
    } catch (e) {
      debugPrint('[PayoutRequestService] Rider payout failed: $e');
      await _firestore.collection(_collection).doc(request.id).update({
        'status': PayoutRequestStatus.failed.name,
        'errorMessage': e.toString(),
      });
      return PayoutResult(success: false, message: e.toString());
    }
  }

  /// Approves a vendor payout request. Vendor payouts are settled by the
  /// owner via manual bank transfer (no payment-gateway integration exists
  /// for vendor accounts), so this records the owner-entered transaction
  /// reference in both the request and a permanent `vendor_payouts` ledger
  /// entry, then marks the request `paid`.
  Future<void> approveVendorRequest({
    required PayoutRequestModel request,
    required String ownerUid,
    required String transactionRef,
    String? notes,
  }) async {
    if (request.type != PayoutRequestType.vendor) {
      throw Exception('Not a vendor payout request');
    }
    if (transactionRef.trim().isEmpty) {
      throw Exception('A transaction reference is required to mark a vendor payout as paid');
    }

    final batch = _firestore.batch();

    final requestRef = _firestore.collection(_collection).doc(request.id);
    batch.update(requestRef, {
      'status': PayoutRequestStatus.paid.name,
      'resolvedAt': FieldValue.serverTimestamp(),
      'resolvedBy': ownerUid,
      'transactionId': transactionRef.trim(),
      'notes': notes,
    });

    final ledgerRef = _firestore.collection('vendor_payouts').doc();
    batch.set(ledgerRef, {
      'payoutRequestId': request.id,
      'shopId': request.recipientId,
      'shopName': request.recipientName,
      'amount': request.amount,
      'currency': request.currency,
      'periodStart': Timestamp.fromDate(request.periodStart),
      'periodEnd': Timestamp.fromDate(request.periodEnd),
      'orderCount': request.orderCount,
      'transactionId': transactionRef.trim(),
      'notes': notes,
      'approvedBy': ownerUid,
      'timestamp': FieldValue.serverTimestamp(),
      'status': 'processed',
    });

    await batch.commit();
  }
}
