import 'package:flutter/foundation.dart';
import '../services/ai_insights_service.dart';
import '../services/pricing_advisor_service.dart';
import '../models/pricing_recommendation_model.dart';

class AiInsightsProvider with ChangeNotifier {
  final AIInsightsService _insightsService = AIInsightsService();
  final PricingAdvisorService _pricingAdvisorService = PricingAdvisorService();

  String _dailyBriefing = 'Loading your AI business assistant briefing...';
  List<PricingRecommendationModel> _pricingSuggestions = [];
  bool _isLoading = false;
  String? _errorMessage;

  String get dailyBriefing => _dailyBriefing;
  List<PricingRecommendationModel> get pricingSuggestions => _pricingSuggestions;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  /// Loads the daily AI advisor briefing narrative
  Future<void> loadBriefing(String ownerId, {bool forceRefresh = false}) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      // In a real app, we might check Firestore first.
      // If forceRefresh, we compute a new briefing via Bedrock.
      if (forceRefresh) {
        _dailyBriefing = await _insightsService.generateDailyAdvisorBriefing(ownerId);
      } else {
        // Mock default or read from Firestore collection
        _dailyBriefing = await _insightsService.generateDailyAdvisorBriefing(ownerId);
      }
    } catch (e) {
      _errorMessage = 'Failed to load daily briefing: $e';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Loads pricing recommendations generated by AI
  Future<void> loadPricingSuggestions(String branchId) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _pricingSuggestions = await _insightsService.generatePricingSuggestions(branchId);
    } catch (e) {
      _errorMessage = 'Failed to load pricing suggestions: $e';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Approves a dynamic pricing suggestion and applies the product change
  Future<void> approveSuggestion(String suggestionId, String ownerId) async {
    try {
      await _pricingAdvisorService.approvePricing(suggestionId, ownerId);
      _pricingSuggestions.removeWhere((s) => s.id == suggestionId);
      notifyListeners();
    } catch (e) {
      _errorMessage = 'Failed to approve pricing: $e';
      notifyListeners();
    }
  }

  /// Rejects a dynamic pricing suggestion
  Future<void> rejectSuggestion(String suggestionId, String ownerId) async {
    try {
      await _pricingAdvisorService.rejectPricing(suggestionId, ownerId);
      _pricingSuggestions.removeWhere((s) => s.id == suggestionId);
      notifyListeners();
    } catch (e) {
      _errorMessage = 'Failed to reject pricing: $e';
      notifyListeners();
    }
  }
}
