import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a single item within a reorder template
class ReorderTemplateItem {
  final String productId;
  final String productName;
  final String productImage;
  final String unit;
  final int quantity;
  final double lastPrice;
  final String? selectedVariant;

  const ReorderTemplateItem({
    required this.productId,
    required this.productName,
    required this.productImage,
    required this.unit,
    required this.quantity,
    required this.lastPrice,
    this.selectedVariant,
  });

  factory ReorderTemplateItem.fromMap(Map<String, dynamic> map) {
    return ReorderTemplateItem(
      productId: map['productId'] ?? '',
      productName: map['productName'] ?? '',
      productImage: map['productImage'] ?? '',
      unit: map['unit'] ?? 'piece',
      quantity: map['quantity'] ?? 1,
      lastPrice: (map['lastPrice'] ?? 0.0).toDouble(),
      selectedVariant: map['selectedVariant'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'productId': productId,
      'productName': productName,
      'productImage': productImage,
      'unit': unit,
      'quantity': quantity,
      'lastPrice': lastPrice,
      'selectedVariant': selectedVariant,
    };
  }

  ReorderTemplateItem copyWith({
    String? productId,
    String? productName,
    String? productImage,
    String? unit,
    int? quantity,
    double? lastPrice,
    String? selectedVariant,
  }) {
    return ReorderTemplateItem(
      productId: productId ?? this.productId,
      productName: productName ?? this.productName,
      productImage: productImage ?? this.productImage,
      unit: unit ?? this.unit,
      quantity: quantity ?? this.quantity,
      lastPrice: lastPrice ?? this.lastPrice,
      selectedVariant: selectedVariant ?? this.selectedVariant,
    );
  }
}

/// Represents a saved reorder template (grocery preset)
/// Stored in Firestore: users/{userId}/reorder_templates/{templateId}
class ReorderTemplate {
  final String id;
  final String userId;
  final String name;
  final String? description;
  final List<ReorderTemplateItem> items;
  final bool isAutoGenerated;
  final String? sourceOrderId;
  final DateTime createdAt;
  final DateTime updatedAt;
  final int usageCount;

  const ReorderTemplate({
    required this.id,
    required this.userId,
    required this.name,
    this.description,
    required this.items,
    this.isAutoGenerated = false,
    this.sourceOrderId,
    required this.createdAt,
    required this.updatedAt,
    this.usageCount = 0,
  });

  factory ReorderTemplate.fromMap(Map<String, dynamic> map) {
    return ReorderTemplate(
      id: map['id'] ?? '',
      userId: map['userId'] ?? '',
      name: map['name'] ?? 'My Template',
      description: map['description'],
      items:
          (map['items'] as List<dynamic>?)
              ?.map(
                (item) => ReorderTemplateItem.fromMap(
                  Map<String, dynamic>.from(item as Map),
                ),
              )
              .toList() ??
          [],
      isAutoGenerated: map['isAutoGenerated'] ?? false,
      sourceOrderId: map['sourceOrderId'],
      createdAt: map['createdAt'] != null
          ? (map['createdAt'] is DateTime
                ? map['createdAt']
                : (map['createdAt'] as Timestamp).toDate())
          : DateTime.now(),
      updatedAt: map['updatedAt'] != null
          ? (map['updatedAt'] is DateTime
                ? map['updatedAt']
                : (map['updatedAt'] as Timestamp).toDate())
          : DateTime.now(),
      usageCount: map['usageCount'] ?? 0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'name': name,
      'description': description,
      'items': items.map((item) => item.toMap()).toList(),
      'isAutoGenerated': isAutoGenerated,
      'sourceOrderId': sourceOrderId,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
      'usageCount': usageCount,
    };
  }

  ReorderTemplate copyWith({
    String? id,
    String? userId,
    String? name,
    String? description,
    List<ReorderTemplateItem>? items,
    bool? isAutoGenerated,
    String? sourceOrderId,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? usageCount,
  }) {
    return ReorderTemplate(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      description: description ?? this.description,
      items: items ?? this.items,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      sourceOrderId: sourceOrderId ?? this.sourceOrderId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      usageCount: usageCount ?? this.usageCount,
    );
  }

  /// Estimated total based on last known prices
  double get estimatedTotal =>
      items.fold(0.0, (sum, item) => sum + (item.lastPrice * item.quantity));

  /// Total number of unique products
  int get itemCount => items.length;

  /// Total quantity across all items
  int get totalQuantity => items.fold(0, (sum, item) => sum + item.quantity);

  /// Creates a template from a completed order
  static ReorderTemplate fromOrder({
    required String userId,
    required String orderId,
    required String orderNumber,
    required List<Map<String, dynamic>> orderItems,
    String? customName,
  }) {
    final now = DateTime.now();
    return ReorderTemplate(
      id: 'tpl_${userId}_${now.millisecondsSinceEpoch}',
      userId: userId,
      name: customName ?? 'Order #$orderNumber',
      description: 'Auto-saved from order #$orderNumber',
      items: orderItems
          .map(
            (item) => ReorderTemplateItem(
              productId: item['productId'] ?? '',
              productName: item['productName'] ?? '',
              productImage: item['productImage'] ?? '',
              unit: item['unit'] ?? 'piece',
              quantity: item['quantity'] ?? 1,
              lastPrice: (item['price'] ?? 0.0).toDouble(),
              selectedVariant: item['selectedVariant'],
            ),
          )
          .toList(),
      isAutoGenerated: true,
      sourceOrderId: orderId,
      createdAt: now,
      updatedAt: now,
    );
  }
}
