/// Product Generator - Batch 2 (P055-P100)
/// Generates 46 additional products for Fufaji Store
/// Run: dart lib/scripts/generate_products_batch_2.dart

class ProductGeneratorBatch2 {
  static List<Map<String, dynamic>> generateProducts() {
    return [
      // SPICES (P055-P062)
      {
        "id": "P055",
        "name": "हल्दी पाउडर",
        "nameEn": "Turmeric Powder",
        "category": "Spices",
        "price": 120,
        "stock": 150,
        "emoji": "🌿",
        "description": "100% pure turmeric powder. No fillers, premium quality.",
        "descriptionHi": "शुद्ध हल्दी पाउडर, कोई मिलावट नहीं।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P056",
        "name": "काली मिर्च",
        "nameEn": "Black Pepper",
        "category": "Spices",
        "price": 280,
        "stock": 100,
        "emoji": "🫑",
        "description": "Whole black peppercorns. Aromatic, freshly packed.",
        "descriptionHi": "साबुत काली मिर्च, ताजा पैकिंग।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P057",
        "name": "धनिया पाउडर",
        "nameEn": "Coriander Powder",
        "category": "Spices",
        "price": 90,
        "stock": 130,
        "emoji": "🌱",
        "description": "Ground coriander seeds. Fresh aroma, perfect spice blend.",
        "descriptionHi": "धनिया का पाउडर, ताजा और सुगंधित।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P058",
        "name": "जीरा पाउडर",
        "nameEn": "Cumin Powder",
        "category": "Spices",
        "price": 110,
        "stock": 125,
        "emoji": "🫙",
        "description": "Pure cumin powder. No additives, digestive benefits.",
        "descriptionHi": "शुद्ध जीरा पाउडर, पाचन के लिए लाभकारी।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P059",
        "name": "लाल मिर्च पाउडर",
        "nameEn": "Red Chili Powder",
        "category": "Spices",
        "price": 95,
        "stock": 140,
        "emoji": "🌶️",
        "description": "Hot red chili powder. For those who love spice!",
        "descriptionHi": "तीखी लाल मिर्च पाउडर, तेज स्वाद के लिए।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P060",
        "name": "मेथी दाना",
        "nameEn": "Fenugreek Seeds",
        "category": "Spices",
        "price": 85,
        "stock": 110,
        "emoji": "🌾",
        "description": "Fresh fenugreek seeds. Good for health and flavor.",
        "descriptionHi": "ताजा मेथी के दाने, स्वास्थ्य के लिए लाभकारी।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P061",
        "name": "गर्म मसाला",
        "nameEn": "Garam Masala",
        "category": "Spices",
        "price": 200,
        "stock": 120,
        "emoji": "🫙",
        "description": "Aromatic garam masala blend. Perfect for Indian cooking.",
        "descriptionHi": "सुगंधित गर्म मसाला, भारतीय खाना के लिए।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P062",
        "name": "नारियल का तेल",
        "nameEn": "Coconut Oil",
        "category": "Groceries",
        "price": 280,
        "stock": 90,
        "emoji": "🥥",
        "description": "Virgin coconut oil. Cold-pressed, pure, no additives.",
        "descriptionHi": "वर्जिन नारियल का तेल, शुद्ध और अच्छा।",
        "gst": 18,
        "isActive": true,
      },

      // BEVERAGES (P063-P065)
      {
        "id": "P063",
        "name": "चाय की पत्तियां",
        "nameEn": "Tea Leaves",
        "category": "Beverages",
        "price": 150,
        "stock": 160,
        "emoji": "🫖",
        "description": "Premium loose tea leaves. Strong, aromatic flavor.",
        "descriptionHi": "प्रीमियम चाय की पत्तियां, मजबूत सुगंध।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P064",
        "name": "तुरंत कॉफी",
        "nameEn": "Instant Coffee",
        "category": "Beverages",
        "price": 220,
        "stock": 100,
        "emoji": "☕",
        "description": "Premium instant coffee powder. Quick, strong, tasty.",
        "descriptionHi": "तुरंत कॉफी पाउडर, जल्दी तैयार।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P065",
        "name": "हॉट चॉकलेट",
        "nameEn": "Hot Chocolate Mix",
        "category": "Beverages",
        "price": 180,
        "stock": 95,
        "emoji": "🍫",
        "description": "Instant hot chocolate mix. Sweet, creamy, delicious.",
        "descriptionHi": "हॉट चॉकलेट मिक्स, मीठा और मलाईदार।",
        "gst": 18,
        "isActive": true,
      },

      // SNACKS (P066-P075)
      {
        "id": "P066",
        "name": "बूंदी के लड्डू",
        "nameEn": "Boondi Laddoo",
        "category": "Snacks",
        "price": 180,
        "stock": 80,
        "emoji": "🫒",
        "description": "Sweet boondi laddoos. Homemade taste, fresh daily.",
        "descriptionHi": "मीठे बूंदी के लड्डू, घर जैसा स्वाद।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P067",
        "name": "मूंगफली",
        "nameEn": "Peanuts",
        "category": "Snacks",
        "price": 60,
        "stock": 200,
        "emoji": "🥜",
        "description": "Roasted salted peanuts. Crunchy, protein-rich.",
        "descriptionHi": "भुनी हुई मूंगफली, प्रोटीन युक्त।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P068",
        "name": "नमकीन मिक्स",
        "nameEn": "Savory Snack Mix",
        "category": "Snacks",
        "price": 120,
        "stock": 140,
        "emoji": "🧂",
        "description": "Mixed savory snacks. Tasty, crunchy, perfect for tea time.",
        "descriptionHi": "नमकीन का मिश्रण, चाय के साथ परफेक्ट।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P069",
        "name": "चिक्की",
        "nameEn": "Peanut Brittle",
        "category": "Snacks",
        "price": 140,
        "stock": 110,
        "emoji": "🍯",
        "description": "Homemade peanut brittle. Crunchy, sweet, traditional.",
        "descriptionHi": "घर जैसी चिक्की, पारंपरिक स्वाद।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P070",
        "name": "सूजी के लड्डू",
        "nameEn": "Semolina Laddoo",
        "category": "Snacks",
        "price": 160,
        "stock": 95,
        "emoji": "🟡",
        "description": "Sweet semolina laddoos. Soft, delicious, homemade.",
        "descriptionHi": "मीठे सूजी के लड्डू, नरम और स्वादिष्ट।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P071",
        "name": "अंगूर की किशमिश",
        "nameEn": "Raisins",
        "category": "Snacks",
        "price": 280,
        "stock": 75,
        "emoji": "🍇",
        "description": "Premium raisins. Sweet, healthy, no additives.",
        "descriptionHi": "प्रीमियम किशमिश, मीठी और स्वास्थ्यकर।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P072",
        "name": "काजू",
        "nameEn": "Cashews",
        "category": "Snacks",
        "price": 400,
        "stock": 60,
        "emoji": "🥜",
        "description": "Premium cashew nuts. Roasted, salted, crunchy.",
        "descriptionHi": "प्रीमियम काजू, भुने हुए और नमकीन।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P073",
        "name": "बादाम",
        "nameEn": "Almonds",
        "category": "Snacks",
        "price": 350,
        "stock": 70,
        "emoji": "🫒",
        "description": "Premium almonds. Raw, soaked, healthy snack.",
        "descriptionHi": "प्रीमियम बादाम, कच्चे और स्वास्थ्यकर।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P074",
        "name": "अखरोट",
        "nameEn": "Walnuts",
        "category": "Snacks",
        "price": 320,
        "stock": 65,
        "emoji": "🥜",
        "description": "Premium walnuts. Omega-3 rich, healthy brain food.",
        "descriptionHi": "प्रीमियम अखरोट, मस्तिष्क के लिए अच्छे।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P075",
        "name": "खजूर",
        "nameEn": "Dates",
        "category": "Snacks",
        "price": 300,
        "stock": 80,
        "emoji": "🍯",
        "description": "Dry dates. Sweet, energy-rich, natural.",
        "descriptionHi": "सूखे खजूर, मीठे और ऊर्जावान।",
        "gst": 18,
        "isActive": true,
      },

      // PERSONAL CARE (P076-P085)
      {
        "id": "P076",
        "name": "नहाने का साबुन",
        "nameEn": "Bath Soap",
        "category": "Personal Care",
        "price": 40,
        "stock": 300,
        "emoji": "🧼",
        "description": "Premium bath soap. Moisturizing, fragrant, long-lasting.",
        "descriptionHi": "प्रीमियम नहाने का साबुन, नरम और सुगंधित।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P077",
        "name": "शैम्पू",
        "nameEn": "Shampoo",
        "category": "Personal Care",
        "price": 120,
        "stock": 150,
        "emoji": "🧴",
        "description": "Hair shampoo. Cleans gently, adds shine, reduces dandruff.",
        "descriptionHi": "बाल शैम्पू, कोमल और प्रभावी।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P078",
        "name": "कंडीशनर",
        "nameEn": "Conditioner",
        "category": "Personal Care",
        "price": 100,
        "stock": 130,
        "emoji": "💆",
        "description": "Hair conditioner. Smooths, softens, adds shine.",
        "descriptionHi": "बाल कंडीशनर, नरम और चमकदार।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P079",
        "name": "टूथपेस्ट",
        "nameEn": "Toothpaste",
        "category": "Personal Care",
        "price": 80,
        "stock": 200,
        "emoji": "🪥",
        "description": "Herbal toothpaste. Cavity protection, white teeth, fresh breath.",
        "descriptionHi": "आयुर्वेदिक टूथपेस्ट, मजबूत दांत।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P080",
        "name": "टूथब्रश",
        "nameEn": "Toothbrush",
        "category": "Personal Care",
        "price": 60,
        "stock": 250,
        "emoji": "🪥",
        "description": "Soft bristle toothbrush. Gentle on gums, effective cleaning.",
        "descriptionHi": "नरम ब्रश वाला टूथब्रश, मसूड़ों के लिए सुरक्षित।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P081",
        "name": "बॉडी लोशन",
        "nameEn": "Body Lotion",
        "category": "Personal Care",
        "price": 150,
        "stock": 110,
        "emoji": "🧴",
        "description": "Moisturizing body lotion. Nourishes, softens skin.",
        "descriptionHi": "बॉडी लोशन, त्वचा को नरम करता है।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P082",
        "name": "फेस क्रीम",
        "nameEn": "Face Cream",
        "category": "Personal Care",
        "price": 200,
        "stock": 90,
        "emoji": "🧴",
        "description": "Anti-aging face cream. Reduces wrinkles, brightens skin.",
        "descriptionHi": "फेस क्रीम, झुर्रियों को कम करती है।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P083",
        "name": "डिओडरेंट",
        "nameEn": "Deodorant",
        "category": "Personal Care",
        "price": 120,
        "stock": 140,
        "emoji": "💨",
        "description": "24-hour deodorant. Fresh scent, sweat protection.",
        "descriptionHi": "डिओडरेंट, पसीने से सुरक्षा।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P084",
        "name": "हेयर ऑयल",
        "nameEn": "Hair Oil",
        "category": "Personal Care",
        "price": 140,
        "stock": 120,
        "emoji": "🫒",
        "description": "Coconut hair oil. Nourishes, strengthens, prevents hair fall.",
        "descriptionHi": "नारियल का हेयर ऑयल, बालों को मजबूत करता है।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P085",
        "name": "लिप बाम",
        "nameEn": "Lip Balm",
        "category": "Personal Care",
        "price": 50,
        "stock": 180,
        "emoji": "💄",
        "description": "Moisturizing lip balm. SPF protection, soft lips.",
        "descriptionHi": "लिप बाम, होंठों को नरम रखता है।",
        "gst": 18,
        "isActive": true,
      },

      // HOME CARE (P086-P090)
      {
        "id": "P086",
        "name": "डिटर्जेंट पाउडर",
        "nameEn": "Detergent Powder",
        "category": "Home Care",
        "price": 200,
        "stock": 120,
        "emoji": "🧺",
        "description": "Powerful detergent powder. Cleans tough stains, gentle on fabric.",
        "descriptionHi": "शक्तिशाली डिटर्जेंट पाउडर, कपड़ों के लिए सुरक्षित।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P087",
        "name": "साफ सफाई का तरल",
        "nameEn": "Floor Cleaner",
        "category": "Home Care",
        "price": 120,
        "stock": 100,
        "emoji": "🧹",
        "description": "Multi-purpose floor cleaner. Kills germs, leaves fresh scent.",
        "descriptionHi": "मल्टीपरपस फ्लोर क्लीनर, रोगाणुनाशक।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P088",
        "name": "कीटनाशक स्प्रे",
        "nameEn": "Insect Repellent Spray",
        "category": "Home Care",
        "price": 150,
        "stock": 90,
        "emoji": "🐛",
        "description": "Safe insect repellent spray. Keeps mosquitoes and bugs away.",
        "descriptionHi": "सुरक्षित कीटनाशक स्प्रे, मच्छर भगाता है।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P089",
        "name": "डिशवॉशर लिक्विड",
        "nameEn": "Dishwash Liquid",
        "category": "Home Care",
        "price": 100,
        "stock": 140,
        "emoji": "🍽️",
        "description": "Grease-cutting dish liquid. Gentle on hands, tough on grease.",
        "descriptionHi": "तेल काटने वाला डिशवॉशर लिक्विड, हाथों के लिए हल्का।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P090",
        "name": "लॉन्ड्री सॉफ्टनर",
        "nameEn": "Fabric Softener",
        "category": "Home Care",
        "price": 180,
        "stock": 110,
        "emoji": "👕",
        "description": "Fabric softener. Makes clothes soft and fragrant.",
        "descriptionHi": "कपड़ों को नरम करने वाला, सुगंधित।",
        "gst": 18,
        "isActive": true,
      },

      // GRAINS & FLOUR (P091-P095)
      {
        "id": "P091",
        "name": "बासमती चावल",
        "nameEn": "Basmati Rice",
        "category": "Groceries",
        "price": 320,
        "stock": 85,
        "emoji": "🍚",
        "description": "Premium basmati rice. Long grains, aromatic, fluffy.",
        "descriptionHi": "प्रीमियम बासमती चावल, लंबे दाने।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P092",
        "name": "मैदा",
        "nameEn": "All Purpose Flour",
        "category": "Groceries",
        "price": 50,
        "stock": 160,
        "emoji": "🌾",
        "description": "Fine all-purpose flour. Perfect for cakes, pastries, and more.",
        "descriptionHi": "बारीक मैदा, केक और पेस्ट्री के लिए।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P093",
        "name": "सोजी",
        "nameEn": "Semolina",
        "category": "Groceries",
        "price": 45,
        "stock": 140,
        "emoji": "🥖",
        "description": "Semolina flour. Great for upma, halwa, and sweets.",
        "descriptionHi": "सूजी का आटा, उपमा और हलवे के लिए।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P094",
        "name": "दलिया",
        "nameEn": "Oats",
        "category": "Groceries",
        "price": 180,
        "stock": 120,
        "emoji": "🥣",
        "description": "Rolled oats. Healthy, protein-rich breakfast cereal.",
        "descriptionHi": "दलिया, स्वास्थ्यकर और पौष्टिक।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P095",
        "name": "चना दाल",
        "nameEn": "Chana Dal",
        "category": "Groceries",
        "price": 120,
        "stock": 135,
        "emoji": "🫘",
        "description": "Split chickpeas. Protein-rich, cooks quickly.",
        "descriptionHi": "चना दाल, प्रोटीन युक्त और जल्दी पकता है।",
        "gst": 18,
        "isActive": true,
      },

      // ADDITIONAL (P096-P100)
      {
        "id": "P096",
        "name": "अरहर की दाल",
        "nameEn": "Pigeon Peas",
        "category": "Groceries",
        "price": 140,
        "stock": 110,
        "emoji": "🌾",
        "description": "Yellow pigeon peas. Delicious dal for sambar and curries.",
        "descriptionHi": "अरहर की दाल, संभार के लिए बेहतरीन।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P097",
        "name": "मूंग दाल",
        "nameEn": "Mung Beans",
        "category": "Groceries",
        "price": 130,
        "stock": 125,
        "emoji": "🫘",
        "description": "Green mung beans. Light, easy to digest, nutritious.",
        "descriptionHi": "मूंग दाल, हल्की और पौष्टिक।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P098",
        "name": "जुवारी का आटा",
        "nameEn": "Jowar Flour",
        "category": "Groceries",
        "price": 55,
        "stock": 95,
        "emoji": "🌾",
        "description": "Jowar flour. Gluten-free, nutritious, traditional.",
        "descriptionHi": "जुवारी का आटा, ग्लूटन फ्री।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P099",
        "name": "मक्के का आटा",
        "nameEn": "Corn Flour",
        "category": "Groceries",
        "price": 60,
        "stock": 120,
        "emoji": "🌽",
        "description": "Corn flour. Smooth, versatile, perfect for gravies.",
        "descriptionHi": "मक्के का आटा, ग्रेवी के लिए परफेक्ट।",
        "gst": 18,
        "isActive": true,
      },
      {
        "id": "P100",
        "name": "साबुदाना",
        "nameEn": "Tapioca Pearls",
        "category": "Groceries",
        "price": 70,
        "stock": 100,
        "emoji": "⚪",
        "description": "Tapioca pearls. Perfect for upma, khichdi, traditional recipes.",
        "descriptionHi": "साबुदाना, उपमा के लिए परफेक्ट।",
        "gst": 18,
        "isActive": true,
      },
    ];
  }

  static void printStats() {
    final products = generateProducts();
    print("\n" + "="*70);
    print("Product Generation - Batch 2 (P055-P100) STATISTICS");
    print("="*70);
    print("\nTotal Products: ${products.length}");
    print("Price Range: Rs.${products.map((p) => p['price'] as int).reduce((a, b) => a < b ? a : b)} - Rs.${products.map((p) => p['price'] as int).reduce((a, b) => a > b ? a : b)}");

    int totalStock = products.fold(0, (sum, p) => sum + (p['stock'] as int));
    print("Total Stock: $totalStock items");

    double totalValue = products.fold(0.0, (sum, p) {
      return sum + ((p['price'] as int) * (p['stock'] as int));
    });
    print("Total Inventory Value: Rs.${totalValue.toStringAsFixed(2)}");

    final categories = <String, int>{};
    for (var p in products) {
      final cat = p['category'] as String;
      categories[cat] = (categories[cat] ?? 0) + 1;
    }

    print("\nProducts by Category:");
    categories.forEach((cat, count) {
      print("   $cat: $count products");
    });

    print("\n" + "="*70 + "\n");
  }
}

void main() {
  ProductGeneratorBatch2.printStats();
}
