/// Seed script for 100 test products to Firestore
/// Run this once to populate the initial product database
///
/// Products cover key categories:
/// - Vegetables (15)
/// - Grains & Flour (12)
/// - Spices (20)
/// - Oils & Ghee (8)
/// - Rice (8)
/// - Dairy (10)
/// - Pulses (7)
/// - Snacks (10)
/// - Biscuits (7)
/// - Sugar & Jaggery (6)
///
/// USAGE: Call seedProducts100(firestore) from your admin panel or setup screen
/// Example: await seedProducts100(FirebaseFirestore.instance);

import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/product_model.dart';
import '../utils/monetary_value.dart';

Future<void> seedProducts100(FirebaseFirestore firestore) async {
  print('[Seed] Starting to seed 100 test products...');
  final batch = firestore.batch();
  final productsRef = firestore.collection('products');

  final products = _generate100Products();
  int batchCount = 0;

  for (final product in products) {
    final docRef = productsRef.doc();
    batch.set(docRef, product.toMap());
    batchCount++;

    // Firestore batch is limited to 500 writes
    if (batchCount % 100 == 0) {
      await batch.commit();
      print('[Seed] Committed $batchCount products...');
    }
  }

  // Commit any remaining
  if (batchCount % 100 != 0) {
    await batch.commit();
  }

  print('[Seed] ✅ Seeded $batchCount products successfully!');
}

List<ProductModel> _generate100Products() {
  final products = <ProductModel>[];

  // VEGETABLES (15)
  products.addAll([
    _createProduct(
      name: 'Potato',
      hindiName: 'आलू',
      category: 'Vegetables',
      keywords: ['aloo', 'potato', 'आलू', 'spud'],
      price: 30.0,
      mrpPrice: 35.0,
      unit: 'kg',
      description: 'Fresh organic potatoes rich in carbs and vitamins',
      nutrition: {
        'Carbs': '17g',
        'Protein': '2g',
        'Fiber': '2g',
        'Potassium': '421mg',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=Potato',
      tags: ['organic', 'fresh', 'staple'],
    ),
    _createProduct(
      name: 'Onion',
      hindiName: 'प्याज़',
      category: 'Vegetables',
      keywords: ['pyaaj', 'onion', 'प्याज़', 'bulb'],
      price: 40.0,
      mrpPrice: 45.0,
      unit: 'kg',
      description: 'Red onions with strong flavor for cooking',
      nutrition: {
        'Calories': '40',
        'Carbs': '9g',
        'Protein': '1g',
        'Fiber': '1.7g',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=Onion',
      tags: ['fresh', 'staple'],
    ),
    _createProduct(
      name: 'Tomato',
      hindiName: 'टमाटर',
      category: 'Vegetables',
      keywords: ['tamatar', 'tomato', 'टमाटर', 'red'],
      price: 35.0,
      mrpPrice: 40.0,
      unit: 'kg',
      description: 'Ripe red tomatoes perfect for curry',
      nutrition: {
        'Calories': '18',
        'Carbs': '3.9g',
        'Protein': '0.9g',
        'VitaminC': '17mg',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Tomato',
      tags: ['fresh', 'seasonal'],
    ),
    _createProduct(
      name: 'Garlic',
      hindiName: 'लहसुन',
      category: 'Vegetables',
      keywords: ['lahsun', 'garlic', 'लहसुन', 'bulb'],
      price: 60.0,
      mrpPrice: 70.0,
      unit: 'kg',
      description: 'Pungent garlic bulbs for flavoring',
      nutrition: {
        'Calories': '149',
        'Carbs': '33g',
        'Protein': '6g',
        'Selenium': '167mcg',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=Garlic',
      tags: ['fresh', 'spice-base'],
    ),
    _createProduct(
      name: 'Ginger',
      hindiName: 'अदरक',
      category: 'Vegetables',
      keywords: ['adrak', 'ginger', 'अदरक', 'root'],
      price: 50.0,
      mrpPrice: 60.0,
      unit: 'kg',
      description: 'Fresh ginger root for tea and cooking',
      nutrition: {
        'Calories': '80',
        'Carbs': '18g',
        'Protein': '1.8g',
        'Potassium': '415mg',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Ginger',
      tags: ['fresh', 'medicinal'],
    ),
    _createProduct(
      name: 'Spinach',
      hindiName: 'पालक',
      category: 'Vegetables',
      keywords: ['palak', 'spinach', 'पालक', 'leafy'],
      price: 25.0,
      mrpPrice: 30.0,
      unit: 'bunch',
      description: 'Fresh green spinach leaves',
      nutrition: {
        'Calories': '23',
        'Iron': '2.7mg',
        'Protein': '2.9g',
        'Calcium': '99mg',
      },
      stock: 60,
      imageUrl:
          'https://via.placeholder.com/300?text=Spinach',
      tags: ['fresh', 'healthy'],
    ),
    _createProduct(
      name: 'Coriander Leaves',
      hindiName: 'धनिया',
      category: 'Vegetables',
      keywords: ['dhania', 'coriander', 'धनिया', 'cilantro'],
      price: 15.0,
      mrpPrice: 20.0,
      unit: 'bunch',
      description: 'Fresh coriander for garnish',
      nutrition: {
        'Calories': '23',
        'VitaminK': '310mcg',
        'VitaminC': '27mg',
        'Iron': '1.2mg',
      },
      stock: 50,
      imageUrl:
          'https://via.placeholder.com/300?text=Coriander',
      tags: ['fresh', 'garnish'],
    ),
    _createProduct(
      name: 'Carrot',
      hindiName: 'गाजर',
      category: 'Vegetables',
      keywords: ['gajar', 'carrot', 'गाजर', 'root'],
      price: 28.0,
      mrpPrice: 32.0,
      unit: 'kg',
      description: 'Orange carrots rich in beta-carotene',
      nutrition: {
        'Calories': '41',
        'Carbs': '10g',
        'VitaminA': '835mcg',
        'Fiber': '2.8g',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Carrot',
      tags: ['fresh', 'healthy'],
    ),
    _createProduct(
      name: 'Cabbage',
      hindiName: 'बंदगोभी',
      category: 'Vegetables',
      keywords: ['bandh gobhi', 'cabbage', 'बंदगोभी'],
      price: 20.0,
      mrpPrice: 25.0,
      unit: 'kg',
      description: 'Green cabbage for salads and cooking',
      nutrition: {
        'Calories': '25',
        'Carbs': '5.8g',
        'Protein': '1.3g',
        'VitaminC': '36.6mg',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=Cabbage',
      tags: ['fresh'],
    ),
    _createProduct(
      name: 'Bell Pepper',
      hindiName: 'शिमला मिर्च',
      category: 'Vegetables',
      keywords: ['shimla mirch', 'bell pepper', 'शिमला मिर्च'],
      price: 45.0,
      mrpPrice: 55.0,
      unit: 'kg',
      description: 'Colorful bell peppers for cooking',
      nutrition: {
        'Calories': '31',
        'VitaminC': '80.4mg',
        'Carbs': '6g',
        'Fiber': '2.2g',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=BellPepper',
      tags: ['fresh', 'colorful'],
    ),
    _createProduct(
      name: 'Capsicum',
      hindiName: 'लंबी मिर्च',
      category: 'Vegetables',
      keywords: ['mirch', 'capsicum', 'लंबी मिर्च', 'pepper'],
      price: 50.0,
      mrpPrice: 60.0,
      unit: 'kg',
      description: 'Long green chili peppers for cooking',
      nutrition: {
        'Calories': '40',
        'VitaminC': '60mg',
        'Carbs': '9g',
        'Fiber': '1.5g',
      },
      stock: 75,
      imageUrl:
          'https://via.placeholder.com/300?text=Capsicum',
      tags: ['fresh', 'spicy'],
    ),
    _createProduct(
      name: 'Cucumber',
      hindiName: 'खीरा',
      category: 'Vegetables',
      keywords: ['khira', 'cucumber', 'खीरा'],
      price: 22.0,
      mrpPrice: 28.0,
      unit: 'kg',
      description: 'Fresh cucumbers for salads',
      nutrition: {
        'Calories': '16',
        'Carbs': '3.6g',
        'Protein': '0.7g',
        'Water': '95.2g',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Cucumber',
      tags: ['fresh', 'salad'],
    ),
    _createProduct(
      name: 'Broccoli',
      hindiName: 'ब्रोकोली',
      category: 'Vegetables',
      keywords: ['broccoli', 'ब्रोकोली', 'green'],
      price: 65.0,
      mrpPrice: 80.0,
      unit: 'kg',
      description: 'Fresh broccoli rich in vitamins',
      nutrition: {
        'Calories': '34',
        'VitaminC': '89.2mg',
        'Protein': '2.8g',
        'Calcium': '47mg',
      },
      stock: 50,
      imageUrl:
          'https://via.placeholder.com/300?text=Broccoli',
      tags: ['fresh', 'healthy', 'premium'],
    ),
  ]);

  // GRAINS & FLOUR (12)
  products.addAll([
    _createProduct(
      name: 'Wheat Flour',
      hindiName: 'गेहूं का आटा',
      category: 'Grains & Flour',
      keywords: ['ata', 'wheat flour', 'गेहूं का आटा', 'maida'],
      price: 35.0,
      mrpPrice: 40.0,
      unit: 'kg',
      description: 'Fine wheat flour for bread and rotis',
      nutrition: {
        'Calories': '364',
        'Protein': '10g',
        'Carbs': '76g',
        'Fiber': '2.7g',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=WheatFlour',
      tags: ['staple', 'organic'],
      brand: 'Pillsbury',
    ),
    _createProduct(
      name: 'Rice Flour',
      hindiName: 'चावल का आटा',
      category: 'Grains & Flour',
      keywords: ['rice flour', 'चावल का आटा'],
      price: 45.0,
      mrpPrice: 55.0,
      unit: 'kg',
      description: 'Fine rice flour for dosa and idli',
      nutrition: {
        'Calories': '366',
        'Carbs': '80g',
        'Protein': '6g',
        'Fiber': '0.4g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=RiceFlour',
      tags: ['staple'],
      brand: 'Aashirvaad',
    ),
    _createProduct(
      name: 'Besan (Gram Flour)',
      hindiName: 'बेसन',
      category: 'Grains & Flour',
      keywords: ['besan', 'gram flour', 'बेसन', 'chickpea flour'],
      price: 60.0,
      mrpPrice: 70.0,
      unit: 'kg',
      description: 'Fine gram flour for pakoras and sweets',
      nutrition: {
        'Calories': '387',
        'Protein': '22g',
        'Carbs': '58g',
        'Fiber': '10g',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=Besan',
      tags: ['staple'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Cornflour',
      hindiName: 'मक्के का आटा',
      category: 'Grains & Flour',
      keywords: ['cornflour', 'मक्के का आटा', 'corn starch'],
      price: 55.0,
      mrpPrice: 65.0,
      unit: 'kg',
      description: 'Cornflour for thickening and cooking',
      nutrition: {
        'Calories': '381',
        'Carbs': '91g',
        'Protein': '3.3g',
        'Fiber': '1.2g',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Cornflour',
      tags: ['cooking'],
      brand: 'Fiddle Faddle',
    ),
    _createProduct(
      name: 'Semolina (Suji)',
      hindiName: 'सूजी',
      category: 'Grains & Flour',
      keywords: ['suji', 'semolina', 'सूजी'],
      price: 40.0,
      mrpPrice: 48.0,
      unit: 'kg',
      description: 'Semolina for upma and khichdi',
      nutrition: {
        'Calories': '360',
        'Carbs': '73g',
        'Protein': '12g',
        'Fiber': '3.7g',
      },
      stock: 110,
      imageUrl:
          'https://via.placeholder.com/300?text=Suji',
      tags: ['staple'],
      brand: 'Aashirvaad',
    ),
    _createProduct(
      name: 'Oats',
      hindiName: 'जई',
      category: 'Grains & Flour',
      keywords: ['oats', 'जई', 'rolled oats'],
      price: 80.0,
      mrpPrice: 100.0,
      unit: 'kg',
      description: 'Rolled oats for breakfast',
      nutrition: {
        'Calories': '389',
        'Protein': '17g',
        'Carbs': '66g',
        'Fiber': '10g',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=Oats',
      tags: ['healthy', 'breakfast'],
      brand: 'Quaker',
    ),
    _createProduct(
      name: 'Barley',
      hindiName: 'जौ',
      category: 'Grains & Flour',
      keywords: ['jau', 'barley', 'जौ'],
      price: 45.0,
      mrpPrice: 55.0,
      unit: 'kg',
      description: 'Barley grains for soups',
      nutrition: {
        'Calories': '354',
        'Protein': '12g',
        'Carbs': '73g',
        'Fiber': '17g',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Barley',
      tags: ['healthy'],
    ),
    _createProduct(
      name: 'Ragi Flour',
      hindiName: 'राजी का आटा',
      category: 'Grains & Flour',
      keywords: ['ragi', 'ragi flour', 'राजी', 'finger millet'],
      price: 55.0,
      mrpPrice: 65.0,
      unit: 'kg',
      description: 'Ragi flour for nutritious porridge',
      nutrition: {
        'Calories': '330',
        'Calcium': '344mg',
        'Protein': '7.3g',
        'Fiber': '3.6g',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=Ragi',
      tags: ['healthy', 'nutritious'],
    ),
    _createProduct(
      name: 'Millet',
      hindiName: 'बाजरा',
      category: 'Grains & Flour',
      keywords: ['bajra', 'millet', 'बाजरा', 'pearl millet'],
      price: 50.0,
      mrpPrice: 60.0,
      unit: 'kg',
      description: 'Millet grains for rotis',
      nutrition: {
        'Calories': '378',
        'Protein': '11g',
        'Carbs': '73g',
        'Fiber': '8.5g',
      },
      stock: 75,
      imageUrl:
          'https://via.placeholder.com/300?text=Millet',
      tags: ['healthy', 'staple'],
    ),
    _createProduct(
      name: 'Tapioca',
      hindiName: 'साबूदाना',
      category: 'Grains & Flour',
      keywords: ['sabudana', 'tapioca', 'साबूदाना'],
      price: 35.0,
      mrpPrice: 42.0,
      unit: 'kg',
      description: 'Sabudana pearls for khichdi',
      nutrition: {
        'Calories': '358',
        'Carbs': '88g',
        'Protein': '0.2g',
        'Fiber': '0.9g',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Tapioca',
      tags: ['staple'],
    ),
  ]);

  // SPICES (20)
  products.addAll([
    _createProduct(
      name: 'Turmeric Powder',
      hindiName: 'हल्दी पाउडर',
      category: 'Spices & Condiments',
      keywords: ['haldi', 'turmeric', 'हल्दी', 'golden'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: '500g',
      description: 'Pure turmeric powder with high curcumin',
      nutrition: {
        'Curcumin': '3-5%',
        'Calcium': '168mg',
        'Iron': '8.83mg',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=Turmeric',
      tags: ['spice', 'medicinal'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Chili Powder',
      hindiName: 'लाल मिर्च पाउडर',
      category: 'Spices & Condiments',
      keywords: ['mirch', 'chili powder', 'लाल मिर्च', 'red chili'],
      price: 150.0,
      mrpPrice: 180.0,
      unit: '500g',
      description: 'Spicy red chili powder',
      nutrition: {
        'Capsaicin': 'High',
        'VitaminC': '76mg',
        'Iron': '1.9mg',
      },
      stock: 180,
      imageUrl:
          'https://via.placeholder.com/300?text=ChiliPowder',
      tags: ['spice', 'hot'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Cumin Seeds',
      hindiName: 'जीरा',
      category: 'Spices & Condiments',
      keywords: ['jeera', 'cumin', 'जीरा'],
      price: 200.0,
      mrpPrice: 250.0,
      unit: '500g',
      description: 'Fragrant cumin seeds',
      nutrition: {
        'Iron': '66.4mg',
        'Manganese': '1.3mg',
        'Calcium': '931mg',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=Cumin',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Coriander Seeds',
      hindiName: 'धनिया दाने',
      category: 'Spices & Condiments',
      keywords: ['dhania', 'coriander seeds', 'धनिया'],
      price: 180.0,
      mrpPrice: 220.0,
      unit: '500g',
      description: 'Aromatic coriander seeds',
      nutrition: {
        'Fiber': '41.9g',
        'Protein': '12g',
        'Iron': '21.77mg',
      },
      stock: 140,
      imageUrl:
          'https://via.placeholder.com/300?text=Coriander',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Black Pepper',
      hindiName: 'काली मिर्च',
      category: 'Spices & Condiments',
      keywords: ['kali mirch', 'black pepper', 'काली मिर्च'],
      price: 220.0,
      mrpPrice: 280.0,
      unit: '500g',
      description: 'Premium black pepper',
      nutrition: {
        'Piperine': '5-9%',
        'Manganese': '1.3mg',
        'Iron': '10.95mg',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=BlackPepper',
      tags: ['spice', 'premium'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Cardamom (Green)',
      hindiName: 'हरी इलायची',
      category: 'Spices & Condiments',
      keywords: ['elaichi', 'cardamom', 'हरी इलायची', 'green'],
      price: 400.0,
      mrpPrice: 500.0,
      unit: '100g',
      description: 'Aromatic green cardamom',
      nutrition: {
        'Cineol': '40-50%',
        'Calcium': '383mg',
        'Iron': '10.2mg',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=Cardamom',
      tags: ['spice', 'premium'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Cinnamon',
      hindiName: 'दालचीनी',
      category: 'Spices & Condiments',
      keywords: ['dalchini', 'cinnamon', 'दालचीनी'],
      price: 180.0,
      mrpPrice: 220.0,
      unit: '100g',
      description: 'Sweet cinnamon sticks',
      nutrition: {
        'Cinnamaldehyde': 'High',
        'Calcium': '1002mg',
        'Iron': '8.32mg',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Cinnamon',
      tags: ['spice', 'sweet'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Cloves',
      hindiName: 'लौंग',
      category: 'Spices & Condiments',
      keywords: ['laung', 'cloves', 'लौंग'],
      price: 280.0,
      mrpPrice: 350.0,
      unit: '100g',
      description: 'Aromatic cloves',
      nutrition: {
        'Eugenol': 'High',
        'Calcium': '666mg',
        'Iron': '8.75mg',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=Cloves',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Nutmeg',
      hindiName: 'जायफल',
      category: 'Spices & Condiments',
      keywords: ['jayifal', 'nutmeg', 'जायफल'],
      price: 300.0,
      mrpPrice: 380.0,
      unit: '100g',
      description: 'Whole nutmeg seeds',
      nutrition: {
        'Myristicin': 'High',
        'Manganese': '3.0mg',
        'Copper': '0.6mg',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Nutmeg',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Fenugreek Seeds',
      hindiName: 'मेथी दाने',
      category: 'Spices & Condiments',
      keywords: ['methi', 'fenugreek', 'मेथी', 'seeds'],
      price: 90.0,
      mrpPrice: 120.0,
      unit: '500g',
      description: 'Fenugreek seeds for cooking',
      nutrition: {
        'Iron': '8.84mg',
        'Protein': '23g',
        'Fiber': '24g',
      },
      stock: 110,
      imageUrl:
          'https://via.placeholder.com/300?text=Fenugreek',
      tags: ['spice'],
    ),
    _createProduct(
      name: 'Asafoetida',
      hindiName: 'हींग',
      category: 'Spices & Condiments',
      keywords: ['hing', 'asafoetida', 'हींग'],
      price: 250.0,
      mrpPrice: 320.0,
      unit: '100g',
      description: 'Pungent asafoetida for flavoring',
      nutrition: {
        'Sulfur': 'High',
        'Carbs': '64g',
        'Protein': '4g',
      },
      stock: 60,
      imageUrl:
          'https://via.placeholder.com/300?text=Hing',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Chaat Masala',
      hindiName: 'चाट मसाला',
      category: 'Spices & Condiments',
      keywords: ['chaat masala', 'चाट मसाला', 'tangy'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: '250g',
      description: 'Tangy spice blend for chaats',
      nutrition: {
        'Sodium': '3.7g',
        'Potassium': '1050mg',
      },
      stock: 140,
      imageUrl:
          'https://via.placeholder.com/300?text=ChatMasala',
      tags: ['spice', 'blend'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Garam Masala',
      hindiName: 'गर्म मसाला',
      category: 'Spices & Condiments',
      keywords: ['garam masala', 'गर्म मसाला', 'warm spices'],
      price: 140.0,
      mrpPrice: 180.0,
      unit: '250g',
      description: 'Warm spice blend',
      nutrition: {
        'Iron': '10mg',
        'Calcium': '200mg',
      },
      stock: 160,
      imageUrl:
          'https://via.placeholder.com/300?text=GaramMasala',
      tags: ['spice', 'blend'],
      brand: 'MDH',
    ),
    _createProduct(
      name: 'Curry Leaves',
      hindiName: 'करी पत्ते',
      category: 'Spices & Condiments',
      keywords: ['curry leaves', 'करी पत्ते', 'leaves'],
      price: 20.0,
      mrpPrice: 30.0,
      unit: 'bunch',
      description: 'Fresh curry leaves',
      nutrition: {
        'VitaminA': '4640 IU',
        'Calcium': '830mg',
        'Iron': '0.93mg',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=CurryLeaves',
      tags: ['spice', 'fresh'],
    ),
    _createProduct(
      name: 'Red Chili Whole',
      hindiName: 'लाल मिर्च पूरी',
      category: 'Spices & Condiments',
      keywords: ['mirch', 'red chili', 'लाल मिर्च', 'whole'],
      price: 180.0,
      mrpPrice: 220.0,
      unit: '500g',
      description: 'Whole dried red chili peppers',
      nutrition: {
        'Capsaicin': 'High',
        'VitaminC': '144mg',
        'Iron': '14mg',
      },
      stock: 130,
      imageUrl:
          'https://via.placeholder.com/300?text=RedChili',
      tags: ['spice'],
      brand: 'Everest',
    ),
    _createProduct(
      name: 'Star Anise',
      hindiName: 'चक्र फूल',
      category: 'Spices & Condiments',
      keywords: ['chakra phool', 'star anise', 'चक्र फूल'],
      price: 320.0,
      mrpPrice: 400.0,
      unit: '100g',
      description: 'Star-shaped spice',
      nutrition: {
        'Anethole': 'High',
        'Calcium': '646mg',
        'Iron': '21.75mg',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=StarAnise',
      tags: ['spice'],
      brand: 'Everest',
    ),
  ]);

  // OILS & GHEE (8)
  products.addAll([
    _createProduct(
      name: 'Mustard Oil',
      hindiName: 'सरसों का तेल',
      category: 'Oils & Ghee',
      keywords: ['sarson tel', 'mustard oil', 'सरसों का तेल'],
      price: 180.0,
      mrpPrice: 220.0,
      unit: 'l',
      description: 'Pure mustard oil for cooking',
      nutrition: {
        'Fats': '100g',
        'OmegaFattyAcids': 'High',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=MustardOil',
      tags: ['oil', 'cooking'],
      brand: 'Dhara',
    ),
    _createProduct(
      name: 'Ghee',
      hindiName: 'घी',
      category: 'Oils & Ghee',
      keywords: ['ghee', 'घी', 'clarified butter'],
      price: 450.0,
      mrpPrice: 550.0,
      unit: '500g',
      description: 'Pure cow ghee',
      nutrition: {
        'Fats': '62g',
        'Cholesterol': '256mg',
        'Butyric Acid': 'High',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Ghee',
      tags: ['ghee', 'cooking'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Coconut Oil',
      hindiName: 'नारियल का तेल',
      category: 'Oils & Ghee',
      keywords: ['nariyal tel', 'coconut oil', 'नारियल का तेल'],
      price: 280.0,
      mrpPrice: 350.0,
      unit: 'l',
      description: 'Pure coconut oil',
      nutrition: {
        'Fats': '100g',
        'LauricAcid': 'High',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=CoconutOil',
      tags: ['oil', 'cooking'],
      brand: 'Parachute',
    ),
    _createProduct(
      name: 'Sunflower Oil',
      hindiName: 'सूरजमुखी का तेल',
      category: 'Oils & Ghee',
      keywords: ['surajmukhi tel', 'sunflower oil', 'सूरजमुखी का तेल'],
      price: 140.0,
      mrpPrice: 180.0,
      unit: 'l',
      description: 'Light sunflower oil',
      nutrition: {
        'Fats': '100g',
        'VitaminE': 'High',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=SunflowerOil',
      tags: ['oil', 'cooking'],
      brand: 'Saffola',
    ),
    _createProduct(
      name: 'Olive Oil',
      hindiName: 'जैतून का तेल',
      category: 'Oils & Ghee',
      keywords: ['jaitun tel', 'olive oil', 'जैतून का तेल'],
      price: 350.0,
      mrpPrice: 450.0,
      unit: '500ml',
      description: 'Extra virgin olive oil',
      nutrition: {
        'Fats': '100g',
        'OleicAcid': '73g',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=OliveOil',
      tags: ['oil', 'premium', 'healthy'],
      brand: 'Figaro',
    ),
    _createProduct(
      name: 'Sesame Oil',
      hindiName: 'तिल का तेल',
      category: 'Oils & Ghee',
      keywords: ['til tel', 'sesame oil', 'तिल का तेल'],
      price: 200.0,
      mrpPrice: 250.0,
      unit: '500ml',
      description: 'Fragrant sesame oil',
      nutrition: {
        'Fats': '100g',
        'Lignans': 'High',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=SesameOil',
      tags: ['oil', 'cooking'],
      brand: 'Kadoya',
    ),
    _createProduct(
      name: 'Vegetable Oil',
      hindiName: 'वनस्पति तेल',
      category: 'Oils & Ghee',
      keywords: ['vanaspati tel', 'vegetable oil', 'वनस्पति तेल'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: 'l',
      description: 'Standard cooking oil',
      nutrition: {
        'Fats': '100g',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=VegetableOil',
      tags: ['oil', 'cooking'],
      brand: 'Fortune',
    ),
    _createProduct(
      name: 'Butter',
      hindiName: 'मक्खन',
      category: 'Oils & Ghee',
      keywords: ['makkhan', 'butter', 'मक्खन'],
      price: 320.0,
      mrpPrice: 400.0,
      unit: '500g',
      description: 'Pure cow butter',
      nutrition: {
        'Fats': '81g',
        'VitaminA': '684 IU',
      },
      stock: 110,
      imageUrl:
          'https://via.placeholder.com/300?text=Butter',
      tags: ['dairy', 'cooking'],
      brand: 'Amul',
    ),
  ]);

  // RICE (8)
  products.addAll([
    _createProduct(
      name: 'Basmati Rice',
      hindiName: 'बासमती चावल',
      category: 'Rice',
      keywords: ['basmati', 'basmati rice', 'बासमती चावल', 'long grain'],
      price: 80.0,
      mrpPrice: 100.0,
      unit: 'kg',
      description: 'Premium long-grain basmati rice',
      nutrition: {
        'Calories': '365',
        'Carbs': '80g',
        'Protein': '7g',
        'Fiber': '0.7g',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=BasmatiRice',
      tags: ['rice', 'staple'],
      brand: 'Kohinoor',
    ),
    _createProduct(
      name: 'Brown Rice',
      hindiName: 'भूरा चावल',
      category: 'Rice',
      keywords: ['brown rice', 'भूरा चावल', 'whole grain'],
      price: 70.0,
      mrpPrice: 85.0,
      unit: 'kg',
      description: 'Healthy brown rice',
      nutrition: {
        'Calories': '353',
        'Carbs': '76g',
        'Protein': '7g',
        'Fiber': '3.5g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=BrownRice',
      tags: ['rice', 'healthy'],
      brand: 'Aashirvaad',
    ),
    _createProduct(
      name: 'White Rice',
      hindiName: 'सफ़ेद चावल',
      category: 'Rice',
      keywords: ['white rice', 'सफ़ेद चावल', 'parboiled'],
      price: 50.0,
      mrpPrice: 60.0,
      unit: 'kg',
      description: 'Regular white rice',
      nutrition: {
        'Calories': '358',
        'Carbs': '79g',
        'Protein': '6.3g',
      },
      stock: 250,
      imageUrl:
          'https://via.placeholder.com/300?text=WhiteRice',
      tags: ['rice', 'staple'],
      brand: 'Daawat',
    ),
    _createProduct(
      name: 'Black Rice',
      hindiName: 'काला चावल',
      category: 'Rice',
      keywords: ['black rice', 'काला चावल', 'forbidden rice'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: 'kg',
      description: 'Rare black rice',
      nutrition: {
        'Calories': '354',
        'Carbs': '77g',
        'Anthocyanin': 'High',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=BlackRice',
      tags: ['rice', 'premium'],
    ),
    _createProduct(
      name: 'Red Rice',
      hindiName: 'लाल चावल',
      category: 'Rice',
      keywords: ['red rice', 'लाल चावल'],
      price: 90.0,
      mrpPrice: 110.0,
      unit: 'kg',
      description: 'Red rice with bran intact',
      nutrition: {
        'Calories': '359',
        'Carbs': '79g',
        'Iron': '2.5mg',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=RedRice',
      tags: ['rice', 'healthy'],
    ),
    _createProduct(
      name: 'Arborio Rice',
      hindiName: 'अर्बोरियो चावल',
      category: 'Rice',
      keywords: ['arborio', 'arborio rice', 'अर्बोरियो चावल', 'risotto'],
      price: 140.0,
      mrpPrice: 180.0,
      unit: 'kg',
      description: 'Italian arborio rice for risotto',
      nutrition: {
        'Calories': '365',
        'Carbs': '80g',
        'Protein': '7g',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=ArborioRice',
      tags: ['rice', 'specialty'],
      brand: 'Riso',
    ),
    _createProduct(
      name: 'Jasmine Rice',
      hindiName: 'चमेली चावल',
      category: 'Rice',
      keywords: ['jasmine', 'jasmine rice', 'चमेली चावल', 'fragrant'],
      price: 75.0,
      mrpPrice: 95.0,
      unit: 'kg',
      description: 'Fragrant jasmine rice',
      nutrition: {
        'Calories': '366',
        'Carbs': '81g',
        'Protein': '6g',
      },
      stock: 130,
      imageUrl:
          'https://via.placeholder.com/300?text=JasmineRice',
      tags: ['rice', 'fragrant'],
      brand: 'Thai Smile',
    ),
    _createProduct(
      name: 'Wild Rice',
      hindiName: 'जंगली चावल',
      category: 'Rice',
      keywords: ['wild rice', 'जंगली चावल'],
      price: 250.0,
      mrpPrice: 320.0,
      unit: 'kg',
      description: 'Nutty wild rice',
      nutrition: {
        'Calories': '357',
        'Protein': '15.4g',
        'Fiber': '6g',
      },
      stock: 50,
      imageUrl:
          'https://via.placeholder.com/300?text=WildRice',
      tags: ['rice', 'premium'],
    ),
  ]);

  // DAIRY (10)
  products.addAll([
    _createProduct(
      name: 'Milk',
      hindiName: 'दूध',
      category: 'Dairy & Milk',
      keywords: ['doodh', 'milk', 'दूध', 'cow milk'],
      price: 50.0,
      mrpPrice: 60.0,
      unit: 'l',
      description: 'Fresh cow milk',
      nutrition: {
        'Calories': '61',
        'Protein': '3.2g',
        'Calcium': '113mg',
        'Fat': '3.3g',
      },
      stock: 300,
      imageUrl:
          'https://via.placeholder.com/300?text=Milk',
      tags: ['dairy', 'fresh'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Yogurt',
      hindiName: 'दही',
      category: 'Dairy & Milk',
      keywords: ['dahi', 'yogurt', 'दही', 'curd'],
      price: 30.0,
      mrpPrice: 40.0,
      unit: '500g',
      description: 'Fresh yogurt with live cultures',
      nutrition: {
        'Calories': '59',
        'Protein': '3.5g',
        'Calcium': '121mg',
        'Probiotics': 'High',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=Yogurt',
      tags: ['dairy', 'fresh'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Paneer',
      hindiName: 'पनीर',
      category: 'Dairy & Milk',
      keywords: ['paneer', 'पनीर', 'cheese', 'cottage cheese'],
      price: 280.0,
      mrpPrice: 350.0,
      unit: '500g',
      description: 'Fresh paneer cheese',
      nutrition: {
        'Calories': '265',
        'Protein': '25g',
        'Calcium': '208mg',
        'Fat': '17g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=Paneer',
      tags: ['dairy', 'protein'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Cheese',
      hindiName: 'चीज़',
      category: 'Dairy & Milk',
      keywords: ['cheese', 'चीज़', 'cheddar'],
      price: 400.0,
      mrpPrice: 500.0,
      unit: '200g',
      description: 'Cheddar cheese slices',
      nutrition: {
        'Calories': '402',
        'Protein': '25g',
        'Calcium': '720mg',
        'Fat': '33g',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Cheese',
      tags: ['dairy', 'premium'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Condensed Milk',
      hindiName: 'सघन दूध',
      category: 'Dairy & Milk',
      keywords: ['condensed milk', 'सघन दूध', 'sweetened'],
      price: 140.0,
      mrpPrice: 180.0,
      unit: '397g',
      description: 'Sweetened condensed milk',
      nutrition: {
        'Calories': '330',
        'Carbs': '55g',
        'Protein': '8g',
        'Calcium': '267mg',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=CondensedMilk',
      tags: ['dairy', 'sweets'],
      brand: 'Nestlé',
    ),
    _createProduct(
      name: 'Evaporated Milk',
      hindiName: 'वाष्पित दूध',
      category: 'Dairy & Milk',
      keywords: ['evaporated milk', 'वाष्पित दूध'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: '397g',
      description: 'Evaporated milk',
      nutrition: {
        'Calories': '134',
        'Protein': '6.8g',
        'Calcium': '196mg',
        'Fat': '7.6g',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=EvaporatedMilk',
      tags: ['dairy'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Cream',
      hindiName: 'क्रीम',
      category: 'Dairy & Milk',
      keywords: ['cream', 'क्रीम', 'whipped cream'],
      price: 180.0,
      mrpPrice: 220.0,
      unit: '250ml',
      description: 'Fresh cream',
      nutrition: {
        'Calories': '340',
        'Fat': '36g',
        'Protein': '2.2g',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=Cream',
      tags: ['dairy', 'cooking'],
      brand: 'Amul',
    ),
    _createProduct(
      name: 'Mozzarella Cheese',
      hindiName: 'मोज़ारेला चीज़',
      category: 'Dairy & Milk',
      keywords: ['mozzarella', 'मोज़ारेला', 'cheese'],
      price: 320.0,
      mrpPrice: 400.0,
      unit: '200g',
      description: 'Fresh mozzarella',
      nutrition: {
        'Calories': '280',
        'Protein': '28g',
        'Calcium': '505mg',
        'Fat': '17g',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Mozzarella',
      tags: ['dairy', 'premium'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Buttermilk',
      hindiName: 'छाछ',
      category: 'Dairy & Milk',
      keywords: ['chhach', 'buttermilk', 'छाछ'],
      price: 25.0,
      mrpPrice: 35.0,
      unit: 'l',
      description: 'Fresh buttermilk',
      nutrition: {
        'Calories': '40',
        'Protein': '3.5g',
        'Calcium': '116mg',
        'Probiotics': 'High',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=Buttermilk',
      tags: ['dairy', 'fresh'],
    ),
    _createProduct(
      name: 'Lactose Free Milk',
      hindiName: 'लैक्टोज मुक्त दूध',
      category: 'Dairy & Milk',
      keywords: ['lactose free', 'लैक्टोज मुक्त दूध'],
      price: 90.0,
      mrpPrice: 110.0,
      unit: 'l',
      description: 'Lactose-free milk',
      nutrition: {
        'Calories': '61',
        'Protein': '3.2g',
        'Calcium': '113mg',
        'Lactose': '0mg',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=LactoseFreeMilk',
      tags: ['dairy', 'special'],
      brand: 'Amul',
    ),
  ]);

  // PULSES (7)
  products.addAll([
    _createProduct(
      name: 'Chickpea (Kabuli Chana)',
      hindiName: 'काबुली चना',
      category: 'Pulses',
      keywords: ['kabuli chana', 'chickpea', 'काबुली चना', 'white chickpea'],
      price: 80.0,
      mrpPrice: 100.0,
      unit: 'kg',
      description: 'White chickpeas for dal',
      nutrition: {
        'Calories': '364',
        'Protein': '19g',
        'Carbs': '61g',
        'Fiber': '15g',
      },
      stock: 180,
      imageUrl:
          'https://via.placeholder.com/300?text=Chickpea',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Black Chickpea (Kala Chana)',
      hindiName: 'काला चना',
      category: 'Pulses',
      keywords: ['kala chana', 'black chickpea', 'काला चना'],
      price: 90.0,
      mrpPrice: 110.0,
      unit: 'kg',
      description: 'Black chickpeas',
      nutrition: {
        'Calories': '372',
        'Protein': '21g',
        'Carbs': '62g',
        'Fiber': '16g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=BlackChickpea',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Moong Dal',
      hindiName: 'मूंग दाल',
      category: 'Pulses',
      keywords: ['moong dal', 'mung dal', 'मूंग दाल', 'green gram'],
      price: 85.0,
      mrpPrice: 105.0,
      unit: 'kg',
      description: 'Green moong dal',
      nutrition: {
        'Calories': '347',
        'Protein': '24g',
        'Carbs': '63g',
        'Fiber': '7.6g',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=MoongDal',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Masoor Dal',
      hindiName: 'मसूर दाल',
      category: 'Pulses',
      keywords: ['masoor dal', 'red lentil', 'मसूर दाल'],
      price: 70.0,
      mrpPrice: 90.0,
      unit: 'kg',
      description: 'Red lentils',
      nutrition: {
        'Calories': '353',
        'Protein': '25g',
        'Carbs': '60g',
        'Fiber': '8g',
      },
      stock: 220,
      imageUrl:
          'https://via.placeholder.com/300?text=MasoorDal',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Urad Dal',
      hindiName: 'उड़द दाल',
      category: 'Pulses',
      keywords: ['urad dal', 'black gram', 'उड़द दाल'],
      price: 95.0,
      mrpPrice: 120.0,
      unit: 'kg',
      description: 'Black gram dal',
      nutrition: {
        'Calories': '372',
        'Protein': '26g',
        'Carbs': '60g',
        'Fiber': '6g',
      },
      stock: 160,
      imageUrl:
          'https://via.placeholder.com/300?text=UradDal',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Arhar Dal (Toor Dal)',
      hindiName: 'अरहर दाल',
      category: 'Pulses',
      keywords: ['arhar dal', 'toor dal', 'अरहर दाल', 'pigeon pea'],
      price: 100.0,
      mrpPrice: 125.0,
      unit: 'kg',
      description: 'Pigeon pea dal',
      nutrition: {
        'Calories': '339',
        'Protein': '22g',
        'Carbs': '57g',
        'Fiber': '15g',
      },
      stock: 190,
      imageUrl:
          'https://via.placeholder.com/300?text=ArharDal',
      tags: ['pulse', 'protein'],
    ),
    _createProduct(
      name: 'Kidney Beans',
      hindiName: 'राजमा',
      category: 'Pulses',
      keywords: ['rajma', 'kidney beans', 'राजमा'],
      price: 75.0,
      mrpPrice: 95.0,
      unit: 'kg',
      description: 'Red kidney beans',
      nutrition: {
        'Calories': '333',
        'Protein': '24g',
        'Carbs': '60g',
        'Fiber': '11g',
      },
      stock: 170,
      imageUrl:
          'https://via.placeholder.com/300?text=KidneyBeans',
      tags: ['pulse', 'protein'],
    ),
  ]);

  // SNACKS (10)
  products.addAll([
    _createProduct(
      name: 'Namkeen Mix',
      hindiName: 'नमकीन मिक्स',
      category: 'Snacks',
      keywords: ['namkeen', 'snack mix', 'नमकीन मिक्स'],
      price: 120.0,
      mrpPrice: 150.0,
      unit: '500g',
      description: 'Mixed savory snacks',
      nutrition: {
        'Calories': '500',
        'Fat': '25g',
        'Carbs': '60g',
        'Protein': '10g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=NamkeenMix',
      tags: ['snack', 'savory'],
      brand: 'Haldirams',
    ),
    _createProduct(
      name: 'Bhujia',
      hindiName: 'भुजिया',
      category: 'Snacks',
      keywords: ['bhujia', 'bhujiya', 'भुजिया'],
      price: 100.0,
      mrpPrice: 130.0,
      unit: '500g',
      description: 'Crispy bhujia snack',
      nutrition: {
        'Calories': '520',
        'Fat': '28g',
        'Carbs': '62g',
        'Protein': '8g',
      },
      stock: 140,
      imageUrl:
          'https://via.placeholder.com/300?text=Bhujia',
      tags: ['snack', 'savory'],
      brand: 'Haldirams',
    ),
    _createProduct(
      name: 'Chakli',
      hindiName: 'चकली',
      category: 'Snacks',
      keywords: ['chakli', 'चकली', 'spiral snack'],
      price: 140.0,
      mrpPrice: 170.0,
      unit: '500g',
      description: 'Crispy spiral chakli',
      nutrition: {
        'Calories': '510',
        'Fat': '26g',
        'Carbs': '63g',
        'Protein': '8g',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=Chakli',
      tags: ['snack', 'savory'],
      brand: 'Haldirams',
    ),
    _createProduct(
      name: 'Samosa Chips',
      hindiName: 'समोसा चिप्स',
      category: 'Snacks',
      keywords: ['samosa chips', 'समोसा चिप्स'],
      price: 110.0,
      mrpPrice: 140.0,
      unit: '500g',
      description: 'Samosa flavored chips',
      nutrition: {
        'Calories': '530',
        'Fat': '30g',
        'Carbs': '60g',
        'Protein': '7g',
      },
      stock: 130,
      imageUrl:
          'https://via.placeholder.com/300?text=SamosaChips',
      tags: ['snack', 'savory'],
      brand: 'Lays',
    ),
    _createProduct(
      name: 'Chikhalwali',
      hindiName: 'चिक्हलवली',
      category: 'Snacks',
      keywords: ['chikhalwali', 'चिक्हलवली'],
      price: 130.0,
      mrpPrice: 160.0,
      unit: '500g',
      description: 'Puffed rice snack',
      nutrition: {
        'Calories': '480',
        'Fat': '20g',
        'Carbs': '65g',
        'Protein': '8g',
      },
      stock: 110,
      imageUrl:
          'https://via.placeholder.com/300?text=Chikhalwali',
      tags: ['snack', 'light'],
    ),
    _createProduct(
      name: 'Mixture',
      hindiName: 'मिक्सचर',
      category: 'Snacks',
      keywords: ['mixture', 'मिक्सचर'],
      price: 125.0,
      mrpPrice: 155.0,
      unit: '500g',
      description: 'Mixed roasted snack',
      nutrition: {
        'Calories': '515',
        'Fat': '27g',
        'Carbs': '61g',
        'Protein': '9g',
      },
      stock: 135,
      imageUrl:
          'https://via.placeholder.com/300?text=Mixture',
      tags: ['snack', 'savory'],
    ),
    _createProduct(
      name: 'Corn Flakes Snack',
      hindiName: 'कॉर्न फ्लेक्स स्नैक',
      category: 'Snacks',
      keywords: ['corn flakes', 'कॉर्न फ्लेक्स', 'crispy'],
      price: 90.0,
      mrpPrice: 120.0,
      unit: '500g',
      description: 'Crispy corn flakes',
      nutrition: {
        'Calories': '450',
        'Fat': '18g',
        'Carbs': '68g',
        'Protein': '6g',
      },
      stock: 145,
      imageUrl:
          'https://via.placeholder.com/300?text=CornFlakes',
      tags: ['snack', 'breakfast'],
      brand: 'Kelloggs',
    ),
    _createProduct(
      name: 'Salted Peanuts',
      hindiName: 'नमकीन मूंगफली',
      category: 'Snacks',
      keywords: ['peanuts', 'मूंगफली', 'salted', 'नमकीन'],
      price: 100.0,
      mrpPrice: 130.0,
      unit: '500g',
      description: 'Roasted salted peanuts',
      nutrition: {
        'Calories': '567',
        'Fat': '49g',
        'Protein': '26g',
        'Fiber': '6g',
      },
      stock: 160,
      imageUrl:
          'https://via.placeholder.com/300?text=Peanuts',
      tags: ['snack', 'healthy'],
    ),
    _createProduct(
      name: 'Mixed Nuts',
      hindiName: 'मिश्रित मेवे',
      category: 'Snacks',
      keywords: ['nuts', 'mixed nuts', 'मेवे', 'मिश्रित'],
      price: 280.0,
      mrpPrice: 350.0,
      unit: '500g',
      description: 'Premium mixed nuts',
      nutrition: {
        'Calories': '593',
        'Fat': '51g',
        'Protein': '21g',
        'Fiber': '3g',
      },
      stock: 80,
      imageUrl:
          'https://via.placeholder.com/300?text=MixedNuts',
      tags: ['snack', 'premium', 'healthy'],
    ),
    _createProduct(
      name: 'Roasted Chana',
      hindiName: 'भुना हुआ चना',
      category: 'Snacks',
      keywords: ['chana', 'roasted chana', 'भुना हुआ चना'],
      price: 80.0,
      mrpPrice: 105.0,
      unit: '500g',
      description: 'Roasted chickpeas',
      nutrition: {
        'Calories': '364',
        'Protein': '19g',
        'Carbs': '61g',
        'Fiber': '15g',
      },
      stock: 140,
      imageUrl:
          'https://via.placeholder.com/300?text=RoastedChana',
      tags: ['snack', 'healthy'],
    ),
  ]);

  // BISCUITS (7)
  products.addAll([
    _createProduct(
      name: 'Marie Gold Biscuits',
      hindiName: 'मेरी गोल्ड बिस्कुट',
      category: 'Biscuits & Cookies',
      keywords: ['marie biscuits', 'मेरी बिस्कुट', 'cookies'],
      price: 60.0,
      mrpPrice: 75.0,
      unit: '500g',
      description: 'Classic marie gold biscuits',
      nutrition: {
        'Calories': '465',
        'Carbs': '73g',
        'Fat': '16g',
        'Protein': '6g',
      },
      stock: 200,
      imageUrl:
          'https://via.placeholder.com/300?text=MarieBiscuits',
      tags: ['biscuits', 'tea'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Digestive Biscuits',
      hindiName: 'पाचन बिस्कुट',
      category: 'Biscuits & Cookies',
      keywords: ['digestive', 'digestive biscuits', 'पाचन बिस्कुट'],
      price: 80.0,
      mrpPrice: 100.0,
      unit: '500g',
      description: 'Wholesome digestive biscuits',
      nutrition: {
        'Calories': '467',
        'Carbs': '70g',
        'Fat': '17g',
        'Protein': '7g',
      },
      stock: 180,
      imageUrl:
          'https://via.placeholder.com/300?text=DigestiveBiscuits',
      tags: ['biscuits', 'healthy'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Cream Cracker Biscuits',
      hindiName: 'क्रीम क्रैकर बिस्कुट',
      category: 'Biscuits & Cookies',
      keywords: ['cream crackers', 'क्रीम क्रैकर', 'crackers'],
      price: 70.0,
      mrpPrice: 90.0,
      unit: '500g',
      description: 'Crispy cream crackers',
      nutrition: {
        'Calories': '456',
        'Carbs': '74g',
        'Fat': '14g',
        'Protein': '8g',
      },
      stock: 160,
      imageUrl:
          'https://via.placeholder.com/300?text=CreamCrackers',
      tags: ['biscuits', 'crackers'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Chocolate Chip Cookies',
      hindiName: 'चॉकलेट चिप कुकीज़',
      category: 'Biscuits & Cookies',
      keywords: ['chocolate cookies', 'चॉकलेट कुकीज़', 'cookies'],
      price: 90.0,
      mrpPrice: 120.0,
      unit: '500g',
      description: 'Chocolate chip cookies',
      nutrition: {
        'Calories': '510',
        'Carbs': '65g',
        'Fat': '24g',
        'Protein': '5g',
      },
      stock: 140,
      imageUrl:
          'https://via.placeholder.com/300?text=ChocolateCookies',
      tags: ['biscuits', 'cookies', 'sweet'],
      brand: 'Sunfeast',
    ),
    _createProduct(
      name: 'Oat Biscuits',
      hindiName: 'जई बिस्कुट',
      category: 'Biscuits & Cookies',
      keywords: ['oat biscuits', 'जई बिस्कुट', 'healthy'],
      price: 85.0,
      mrpPrice: 110.0,
      unit: '500g',
      description: 'Healthy oat biscuits',
      nutrition: {
        'Calories': '445',
        'Carbs': '68g',
        'Fat': '15g',
        'Protein': '8g',
        'Fiber': '5g',
      },
      stock: 130,
      imageUrl:
          'https://via.placeholder.com/300?text=OatBiscuits',
      tags: ['biscuits', 'healthy'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Rusks',
      hindiName: 'रस्क',
      category: 'Biscuits & Cookies',
      keywords: ['rusks', 'rusk', 'रस्क'],
      price: 65.0,
      mrpPrice: 85.0,
      unit: '500g',
      description: 'Crispy rusks for tea',
      nutrition: {
        'Calories': '395',
        'Carbs': '80g',
        'Fat': '3g',
        'Protein': '6g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=Rusks',
      tags: ['biscuits', 'tea'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Bourbon Biscuits',
      hindiName: 'बूरबॉन बिस्कुट',
      category: 'Biscuits & Cookies',
      keywords: ['bourbon', 'bourbon biscuits', 'बूरबॉन बिस्कुट'],
      price: 75.0,
      mrpPrice: 95.0,
      unit: '500g',
      description: 'Double chocolate bourbon biscuits',
      nutrition: {
        'Calories': '485',
        'Carbs': '68g',
        'Fat': '20g',
        'Protein': '6g',
      },
      stock: 120,
      imageUrl:
          'https://via.placeholder.com/300?text=BourbonBiscuits',
      tags: ['biscuits', 'cookies', 'chocolate'],
      brand: 'Britannia',
    ),
  ]);

  // SUGAR & JAGGERY (6)
  products.addAll([
    _createProduct(
      name: 'White Sugar',
      hindiName: 'सफ़ेद चीनी',
      category: 'Sugar & Jaggery',
      keywords: ['sugar', 'white sugar', 'सफ़ेद चीनी'],
      price: 35.0,
      mrpPrice: 45.0,
      unit: 'kg',
      description: 'Refined white sugar',
      nutrition: {
        'Calories': '387',
        'Carbs': '100g',
      },
      stock: 300,
      imageUrl:
          'https://via.placeholder.com/300?text=WhiteSugar',
      tags: ['sweetener', 'staple'],
      brand: 'Britannia',
    ),
    _createProduct(
      name: 'Brown Sugar',
      hindiName: 'भूरी चीनी',
      category: 'Sugar & Jaggery',
      keywords: ['brown sugar', 'भूरी चीनी'],
      price: 45.0,
      mrpPrice: 60.0,
      unit: 'kg',
      description: 'Brown muscovado sugar',
      nutrition: {
        'Calories': '380',
        'Carbs': '98g',
      },
      stock: 150,
      imageUrl:
          'https://via.placeholder.com/300?text=BrownSugar',
      tags: ['sweetener'],
    ),
    _createProduct(
      name: 'Jaggery Powder',
      hindiName: 'गुड़ पाउडर',
      category: 'Sugar & Jaggery',
      keywords: ['jaggery', 'gur', 'गुड़', 'jaggery powder'],
      price: 55.0,
      mrpPrice: 70.0,
      unit: 'kg',
      description: 'Pure jaggery powder',
      nutrition: {
        'Calories': '383',
        'Carbs': '98g',
        'Iron': '11mg',
      },
      stock: 180,
      imageUrl:
          'https://via.placeholder.com/300?text=Jaggery',
      tags: ['sweetener', 'organic'],
    ),
    _createProduct(
      name: 'Honey',
      hindiName: 'शहद',
      category: 'Sugar & Jaggery',
      keywords: ['honey', 'शहद'],
      price: 280.0,
      mrpPrice: 350.0,
      unit: 'l',
      description: 'Pure natural honey',
      nutrition: {
        'Calories': '304',
        'Carbs': '82g',
        'Antioxidants': 'High',
      },
      stock: 100,
      imageUrl:
          'https://via.placeholder.com/300?text=Honey',
      tags: ['sweetener', 'organic', 'healthy'],
      brand: 'Dabur',
    ),
    _createProduct(
      name: 'Molasses',
      hindiName: 'गुलकंद',
      category: 'Sugar & Jaggery',
      keywords: ['molasses', 'गुलकंद'],
      price: 100.0,
      mrpPrice: 130.0,
      unit: 'kg',
      description: 'Dark molasses syrup',
      nutrition: {
        'Calories': '290',
        'Carbs': '75g',
        'Iron': '5mg',
      },
      stock: 90,
      imageUrl:
          'https://via.placeholder.com/300?text=Molasses',
      tags: ['sweetener'],
    ),
    _createProduct(
      name: 'Stevia',
      hindiName: 'स्टीविया',
      category: 'Sugar & Jaggery',
      keywords: ['stevia', 'स्टीविया', 'sweetener'],
      price: 150.0,
      mrpPrice: 200.0,
      unit: '250g',
      description: 'Natural stevia sweetener',
      nutrition: {
        'Calories': '0',
        'GlycemicIndex': 'Very Low',
      },
      stock: 70,
      imageUrl:
          'https://via.placeholder.com/300?text=Stevia',
      tags: ['sweetener', 'healthy', 'diet'],
      brand: 'Pure Circle',
    ),
  ]);

  return products;
}

/// Helper to create a ProductModel with sensible defaults
ProductModel _createProduct({
  required String name,
  required String hindiName,
  required String category,
  required List<String> keywords,
  required double price,
  required double mrpPrice,
  required String unit,
  required String description,
  required Map<String, String> nutrition,
  required int stock,
  required String imageUrl,
  List<String>? tags,
  String? brand,
}) {
  return ProductModel(
    id: '',  // Will be generated by Firestore
    name: name,
    hindiName: hindiName,  // NEW
    description: description,
    price: MonetaryValue(price),
    originalPrice: MonetaryValue(mrpPrice),
    discountPercentage: MonetaryValue(100 - (price / mrpPrice * 100)),
    unit: unit,
    categoryId: category.toLowerCase(),
    category: category,
    subCategory: '',
    shopId: 'fufaji-store-1',  // Main Fufaji store
    shopName: 'Fufaji Store',
    imageUrl: imageUrl,
    images: [imageUrl],
    keywords: keywords,  // NEW
    mrpPrice: mrpPrice,  // NEW
    nutrition: nutrition,  // NEW
    rating: 4.5,
    tags: tags ?? [],
    brand: brand,
    barcode: '',
    isAvailable: true,
    stockQuantity: stock,
    district: 'Jaipur',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  );
}
